# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AnalyticsCheckoutAbandonmentGetSummaryResponse,
        AnalyticsCheckoutAbandonmentGetSummaryResponseSummaryItem,
        AnalyticsCheckoutAbandonmentListRequestSeverity,
        AnalyticsCheckoutAbandonmentListRequestStatus,
        AnalyticsCheckoutAbandonmentListResponse,
        AnalyticsCheckoutAbandonmentListResponseAlertsItem,
        AnalyticsCheckoutGetFunnelResponse,
        AnalyticsCheckoutGetFunnelResponseStepsItem,
        AnalyticsCheckoutWinbackGetSummaryResponse,
        AnalyticsCheckoutWinbackGetSummaryResponseByStatus,
        AnalyticsCheckoutWinbackGetSummaryResponseByType,
        AnalyticsCheckoutWinbackListRequestStatus,
        AnalyticsCheckoutWinbackListRequestType,
        AnalyticsCheckoutWinbackListResponse,
        AnalyticsCheckoutWinbackListResponseOpportunitiesItem,
        AnalyticsCheckoutWinbackListResponseOpportunitiesItemOpportunityType,
        AnalyticsCheckoutWinbackListResponseOpportunitiesItemStatus,
        AnalyticsCollectionsGetDsoResponse,
        AnalyticsCollectionsGetDsoResponseTrend,
        AnalyticsCustomersGetLtvResponse,
        AnalyticsCustomersGetLtvResponseCustomersItem,
        AnalyticsCustomersRetrieveResponse,
        AnalyticsInvoicesGetArAgingResponse,
        AnalyticsInvoicesGetArAgingResponseBucketsItem,
        AnalyticsPaymentLinksGetConversionResponse,
        AnalyticsRevenueGetMrrSummaryResponse,
        AnalyticsRevenueGetTimeSeriesRequestGranularity,
        AnalyticsRevenueGetTimeSeriesResponse,
        AnalyticsRevenueGetTimeSeriesResponseDataPointsItem,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "AnalyticsCheckoutAbandonmentGetSummaryResponse": ".types",
    "AnalyticsCheckoutAbandonmentGetSummaryResponseSummaryItem": ".types",
    "AnalyticsCheckoutAbandonmentListRequestSeverity": ".types",
    "AnalyticsCheckoutAbandonmentListRequestStatus": ".types",
    "AnalyticsCheckoutAbandonmentListResponse": ".types",
    "AnalyticsCheckoutAbandonmentListResponseAlertsItem": ".types",
    "AnalyticsCheckoutGetFunnelResponse": ".types",
    "AnalyticsCheckoutGetFunnelResponseStepsItem": ".types",
    "AnalyticsCheckoutWinbackGetSummaryResponse": ".types",
    "AnalyticsCheckoutWinbackGetSummaryResponseByStatus": ".types",
    "AnalyticsCheckoutWinbackGetSummaryResponseByType": ".types",
    "AnalyticsCheckoutWinbackListRequestStatus": ".types",
    "AnalyticsCheckoutWinbackListRequestType": ".types",
    "AnalyticsCheckoutWinbackListResponse": ".types",
    "AnalyticsCheckoutWinbackListResponseOpportunitiesItem": ".types",
    "AnalyticsCheckoutWinbackListResponseOpportunitiesItemOpportunityType": ".types",
    "AnalyticsCheckoutWinbackListResponseOpportunitiesItemStatus": ".types",
    "AnalyticsCollectionsGetDsoResponse": ".types",
    "AnalyticsCollectionsGetDsoResponseTrend": ".types",
    "AnalyticsCustomersGetLtvResponse": ".types",
    "AnalyticsCustomersGetLtvResponseCustomersItem": ".types",
    "AnalyticsCustomersRetrieveResponse": ".types",
    "AnalyticsInvoicesGetArAgingResponse": ".types",
    "AnalyticsInvoicesGetArAgingResponseBucketsItem": ".types",
    "AnalyticsPaymentLinksGetConversionResponse": ".types",
    "AnalyticsRevenueGetMrrSummaryResponse": ".types",
    "AnalyticsRevenueGetTimeSeriesRequestGranularity": ".types",
    "AnalyticsRevenueGetTimeSeriesResponse": ".types",
    "AnalyticsRevenueGetTimeSeriesResponseDataPointsItem": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AnalyticsCheckoutAbandonmentGetSummaryResponse",
    "AnalyticsCheckoutAbandonmentGetSummaryResponseSummaryItem",
    "AnalyticsCheckoutAbandonmentListRequestSeverity",
    "AnalyticsCheckoutAbandonmentListRequestStatus",
    "AnalyticsCheckoutAbandonmentListResponse",
    "AnalyticsCheckoutAbandonmentListResponseAlertsItem",
    "AnalyticsCheckoutGetFunnelResponse",
    "AnalyticsCheckoutGetFunnelResponseStepsItem",
    "AnalyticsCheckoutWinbackGetSummaryResponse",
    "AnalyticsCheckoutWinbackGetSummaryResponseByStatus",
    "AnalyticsCheckoutWinbackGetSummaryResponseByType",
    "AnalyticsCheckoutWinbackListRequestStatus",
    "AnalyticsCheckoutWinbackListRequestType",
    "AnalyticsCheckoutWinbackListResponse",
    "AnalyticsCheckoutWinbackListResponseOpportunitiesItem",
    "AnalyticsCheckoutWinbackListResponseOpportunitiesItemOpportunityType",
    "AnalyticsCheckoutWinbackListResponseOpportunitiesItemStatus",
    "AnalyticsCollectionsGetDsoResponse",
    "AnalyticsCollectionsGetDsoResponseTrend",
    "AnalyticsCustomersGetLtvResponse",
    "AnalyticsCustomersGetLtvResponseCustomersItem",
    "AnalyticsCustomersRetrieveResponse",
    "AnalyticsInvoicesGetArAgingResponse",
    "AnalyticsInvoicesGetArAgingResponseBucketsItem",
    "AnalyticsPaymentLinksGetConversionResponse",
    "AnalyticsRevenueGetMrrSummaryResponse",
    "AnalyticsRevenueGetTimeSeriesRequestGranularity",
    "AnalyticsRevenueGetTimeSeriesResponse",
    "AnalyticsRevenueGetTimeSeriesResponseDataPointsItem",
]
