# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPayoutsClient, RawPayoutsClient
from .types.payouts_list_request_status import PayoutsListRequestStatus
from .types.payouts_list_response import PayoutsListResponse
from .types.payouts_payments_list_response import PayoutsPaymentsListResponse
from .types.payouts_retrieve_response import PayoutsRetrieveResponse


class PayoutsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPayoutsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPayoutsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPayoutsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        status: typing.Optional[PayoutsListRequestStatus] = None,
        gateway: typing.Optional[str] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PayoutsListResponse:
        """
        Retrieve a paginated list of payouts/settlements with optional filters. Results are ordered by creation date (newest first).

        Parameters
        ----------
        status : typing.Optional[PayoutsListRequestStatus]
            Filter by payout status

        gateway : typing.Optional[str]
            Filter by payment gateway (nmi, stripe, etc.)

        created_after : typing.Optional[str]
            ISO 8601 date - only payouts created after this date

        created_before : typing.Optional[str]
            ISO 8601 date - only payouts created before this date

        limit : typing.Optional[float]
            Number of results to return (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayoutsListResponse
            List of payouts

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.payouts.list(
            created_after="2024-01-01T00:00:00Z",
            created_before="2024-12-31T23:59:59Z",
            limit=20.0,
        )
        """
        _response = self._raw_client.list(
            status=status,
            gateway=gateway,
            created_after=created_after,
            created_before=created_before,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PayoutsRetrieveResponse:
        """
        Retrieve a single payout by its public ID (pyt_xxx) or internal UUID.

        Parameters
        ----------
        id : str
            Payout public ID (pyt_xxx) or UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayoutsRetrieveResponse
            Payout details

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.payouts.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def payments_list(
        self,
        id: str,
        *,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PayoutsPaymentsListResponse:
        """
        Retrieve all payments that were included in a specific payout batch.

        Parameters
        ----------
        id : str
            Payout public ID (pyt_xxx) or UUID

        limit : typing.Optional[float]
            Maximum number of results (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayoutsPaymentsListResponse
            List of payments in the payout

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.payouts.payments_list(
            id="id",
        )
        """
        _response = self._raw_client.payments_list(id, limit=limit, offset=offset, request_options=request_options)
        return _response.data


class AsyncPayoutsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPayoutsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPayoutsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPayoutsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        status: typing.Optional[PayoutsListRequestStatus] = None,
        gateway: typing.Optional[str] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PayoutsListResponse:
        """
        Retrieve a paginated list of payouts/settlements with optional filters. Results are ordered by creation date (newest first).

        Parameters
        ----------
        status : typing.Optional[PayoutsListRequestStatus]
            Filter by payout status

        gateway : typing.Optional[str]
            Filter by payment gateway (nmi, stripe, etc.)

        created_after : typing.Optional[str]
            ISO 8601 date - only payouts created after this date

        created_before : typing.Optional[str]
            ISO 8601 date - only payouts created before this date

        limit : typing.Optional[float]
            Number of results to return (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayoutsListResponse
            List of payouts

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payouts.list(
                created_after="2024-01-01T00:00:00Z",
                created_before="2024-12-31T23:59:59Z",
                limit=20.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            status=status,
            gateway=gateway,
            created_after=created_after,
            created_before=created_before,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PayoutsRetrieveResponse:
        """
        Retrieve a single payout by its public ID (pyt_xxx) or internal UUID.

        Parameters
        ----------
        id : str
            Payout public ID (pyt_xxx) or UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayoutsRetrieveResponse
            Payout details

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payouts.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def payments_list(
        self,
        id: str,
        *,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PayoutsPaymentsListResponse:
        """
        Retrieve all payments that were included in a specific payout batch.

        Parameters
        ----------
        id : str
            Payout public ID (pyt_xxx) or UUID

        limit : typing.Optional[float]
            Maximum number of results (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PayoutsPaymentsListResponse
            List of payments in the payout

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.payouts.payments_list(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.payments_list(
            id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data
