# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.order import Order
from ..types.order_list_response import OrderListResponse
from .raw_client import AsyncRawOrdersClient, RawOrdersClient
from .types.create_order_request_billing_type import CreateOrderRequestBillingType
from .types.create_order_request_line_items_item import CreateOrderRequestLineItemsItem
from .types.orders_list_request_billing_type import OrdersListRequestBillingType
from .types.orders_list_request_status import OrdersListRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrdersClient
        """
        return self._raw_client

    def list(
        self,
        *,
        customer_id: typing.Optional[str] = None,
        status: typing.Optional[OrdersListRequestStatus] = None,
        billing_type: typing.Optional[OrdersListRequestBillingType] = None,
        created_gte: typing.Optional[float] = None,
        created_lte: typing.Optional[float] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderListResponse:
        """
        List all orders for the authenticated merchant. Supports filtering and cursor-based pagination.

        Parameters
        ----------
        customer_id : typing.Optional[str]
            Filter by customer ID

        status : typing.Optional[OrdersListRequestStatus]
            Filter by status

        billing_type : typing.Optional[OrdersListRequestBillingType]
            Filter by billing type

        created_gte : typing.Optional[float]
            Filter by created_at >= (Unix timestamp)

        created_lte : typing.Optional[float]
            Filter by created_at <= (Unix timestamp)

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        starting_after : typing.Optional[str]
            Cursor for pagination - return results after this ID

        ending_before : typing.Optional[str]
            Cursor for pagination - return results before this ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderListResponse
            List of orders

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.orders.list()
        """
        _response = self._raw_client.list(
            customer_id=customer_id,
            status=status,
            billing_type=billing_type,
            created_gte=created_gte,
            created_lte=created_lte,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        *,
        line_items: typing.Sequence[CreateOrderRequestLineItemsItem],
        customer_id: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        billing_type: typing.Optional[CreateOrderRequestBillingType] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        notes: typing.Optional[str] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        invoice_id: typing.Optional[str] = OMIT,
        subscription_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new order with line items. Orders start in draft status.

        Parameters
        ----------
        line_items : typing.Sequence[CreateOrderRequestLineItemsItem]
            Order line items (at least one required)

        customer_id : typing.Optional[str]
            Customer ID (optional for guest orders)

        currency : typing.Optional[str]
            Three-letter ISO currency code

        billing_type : typing.Optional[CreateOrderRequestBillingType]
            Billing type. one_time: Single purchase. recurring: Subscription-based.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom key-value metadata

        notes : typing.Optional[str]

        expires_at : typing.Optional[dt.datetime]
            Expiration timestamp for the order

        invoice_id : typing.Optional[str]
            ID of the linked invoice (Commercial Truth)

        subscription_id : typing.Optional[str]
            ID of the linked subscription (for recurring fulfillment)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order created successfully

        Examples
        --------
        from revkeen import RevKeen
        from revkeen.orders import CreateOrderRequestLineItemsItem

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.orders.create(
            line_items=[
                CreateOrderRequestLineItemsItem(
                    description="description",
                    unit_price=1,
                )
            ],
        )
        """
        _response = self._raw_client.create(
            line_items=line_items,
            customer_id=customer_id,
            currency=currency,
            billing_type=billing_type,
            metadata=metadata,
            notes=notes,
            expires_at=expires_at,
            invoice_id=invoice_id,
            subscription_id=subscription_id,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Order:
        """
        Retrieves an order by its ID, including line items.

        Parameters
        ----------
        id : str
            Order ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order details

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.orders.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def pay(
        self,
        id: str,
        *,
        payment_method_id: typing.Optional[str] = OMIT,
        payment_token: typing.Optional[str] = OMIT,
        amount: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Process payment for an order. Creates an invoice and charges the customer's payment method.

        Parameters
        ----------
        id : str
            Order ID

        payment_method_id : typing.Optional[str]
            Saved payment method ID

        payment_token : typing.Optional[str]
            One-time payment token

        amount : typing.Optional[int]
            Partial payment amount in cents (defaults to full amount_due)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order paid successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.orders.pay(
            id="id",
        )
        """
        _response = self._raw_client.pay(
            id,
            payment_method_id=payment_method_id,
            payment_token=payment_token,
            amount=amount,
            request_options=request_options,
        )
        return _response.data

    def cancel(
        self, id: str, *, reason: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> Order:
        """
        Cancels an order. Only orders that haven't been paid or fulfilled can be canceled.

        Parameters
        ----------
        id : str
            Order ID

        reason : typing.Optional[str]
            Reason for cancellation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order canceled successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.orders.cancel(
            id="id",
        )
        """
        _response = self._raw_client.cancel(id, reason=reason, request_options=request_options)
        return _response.data

    def fulfill(
        self,
        id: str,
        *,
        tracking_number: typing.Optional[str] = OMIT,
        carrier: typing.Optional[str] = OMIT,
        line_item_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        notify_customer: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Mark an order as fulfilled. Optionally include shipping tracking information.

        Parameters
        ----------
        id : str
            Order ID

        tracking_number : typing.Optional[str]
            Shipping tracking number

        carrier : typing.Optional[str]
            Shipping carrier (e.g., 'ups', 'fedex', 'usps')

        line_item_ids : typing.Optional[typing.Sequence[str]]
            Specific line items to fulfill (defaults to all)

        notify_customer : typing.Optional[bool]
            Send fulfillment notification to customer

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order fulfilled successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.orders.fulfill(
            id="id",
        )
        """
        _response = self._raw_client.fulfill(
            id,
            tracking_number=tracking_number,
            carrier=carrier,
            line_item_ids=line_item_ids,
            notify_customer=notify_customer,
            request_options=request_options,
        )
        return _response.data


class AsyncOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrdersClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        customer_id: typing.Optional[str] = None,
        status: typing.Optional[OrdersListRequestStatus] = None,
        billing_type: typing.Optional[OrdersListRequestBillingType] = None,
        created_gte: typing.Optional[float] = None,
        created_lte: typing.Optional[float] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderListResponse:
        """
        List all orders for the authenticated merchant. Supports filtering and cursor-based pagination.

        Parameters
        ----------
        customer_id : typing.Optional[str]
            Filter by customer ID

        status : typing.Optional[OrdersListRequestStatus]
            Filter by status

        billing_type : typing.Optional[OrdersListRequestBillingType]
            Filter by billing type

        created_gte : typing.Optional[float]
            Filter by created_at >= (Unix timestamp)

        created_lte : typing.Optional[float]
            Filter by created_at <= (Unix timestamp)

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        starting_after : typing.Optional[str]
            Cursor for pagination - return results after this ID

        ending_before : typing.Optional[str]
            Cursor for pagination - return results before this ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderListResponse
            List of orders

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            customer_id=customer_id,
            status=status,
            billing_type=billing_type,
            created_gte=created_gte,
            created_lte=created_lte,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        *,
        line_items: typing.Sequence[CreateOrderRequestLineItemsItem],
        customer_id: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        billing_type: typing.Optional[CreateOrderRequestBillingType] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        notes: typing.Optional[str] = OMIT,
        expires_at: typing.Optional[dt.datetime] = OMIT,
        invoice_id: typing.Optional[str] = OMIT,
        subscription_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Creates a new order with line items. Orders start in draft status.

        Parameters
        ----------
        line_items : typing.Sequence[CreateOrderRequestLineItemsItem]
            Order line items (at least one required)

        customer_id : typing.Optional[str]
            Customer ID (optional for guest orders)

        currency : typing.Optional[str]
            Three-letter ISO currency code

        billing_type : typing.Optional[CreateOrderRequestBillingType]
            Billing type. one_time: Single purchase. recurring: Subscription-based.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom key-value metadata

        notes : typing.Optional[str]

        expires_at : typing.Optional[dt.datetime]
            Expiration timestamp for the order

        invoice_id : typing.Optional[str]
            ID of the linked invoice (Commercial Truth)

        subscription_id : typing.Optional[str]
            ID of the linked subscription (for recurring fulfillment)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order created successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen
        from revkeen.orders import CreateOrderRequestLineItemsItem

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.create(
                line_items=[
                    CreateOrderRequestLineItemsItem(
                        description="description",
                        unit_price=1,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            line_items=line_items,
            customer_id=customer_id,
            currency=currency,
            billing_type=billing_type,
            metadata=metadata,
            notes=notes,
            expires_at=expires_at,
            invoice_id=invoice_id,
            subscription_id=subscription_id,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Order:
        """
        Retrieves an order by its ID, including line items.

        Parameters
        ----------
        id : str
            Order ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order details

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def pay(
        self,
        id: str,
        *,
        payment_method_id: typing.Optional[str] = OMIT,
        payment_token: typing.Optional[str] = OMIT,
        amount: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Process payment for an order. Creates an invoice and charges the customer's payment method.

        Parameters
        ----------
        id : str
            Order ID

        payment_method_id : typing.Optional[str]
            Saved payment method ID

        payment_token : typing.Optional[str]
            One-time payment token

        amount : typing.Optional[int]
            Partial payment amount in cents (defaults to full amount_due)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order paid successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.pay(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pay(
            id,
            payment_method_id=payment_method_id,
            payment_token=payment_token,
            amount=amount,
            request_options=request_options,
        )
        return _response.data

    async def cancel(
        self, id: str, *, reason: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> Order:
        """
        Cancels an order. Only orders that haven't been paid or fulfilled can be canceled.

        Parameters
        ----------
        id : str
            Order ID

        reason : typing.Optional[str]
            Reason for cancellation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order canceled successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.cancel(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(id, reason=reason, request_options=request_options)
        return _response.data

    async def fulfill(
        self,
        id: str,
        *,
        tracking_number: typing.Optional[str] = OMIT,
        carrier: typing.Optional[str] = OMIT,
        line_item_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        notify_customer: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Order:
        """
        Mark an order as fulfilled. Optionally include shipping tracking information.

        Parameters
        ----------
        id : str
            Order ID

        tracking_number : typing.Optional[str]
            Shipping tracking number

        carrier : typing.Optional[str]
            Shipping carrier (e.g., 'ups', 'fedex', 'usps')

        line_item_ids : typing.Optional[typing.Sequence[str]]
            Specific line items to fulfill (defaults to all)

        notify_customer : typing.Optional[bool]
            Send fulfillment notification to customer

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Order
            Order fulfilled successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.fulfill(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.fulfill(
            id,
            tracking_number=tracking_number,
            carrier=carrier,
            line_item_ids=line_item_ids,
            notify_customer=notify_customer,
            request_options=request_options,
        )
        return _response.data
