# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_businesses_response_pagination import GetBusinessesResponsePagination


class GetBusinessesResponse(UniversalBaseModel):
    data: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Business objects
    """

    pagination: GetBusinessesResponsePagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
