# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.checkout_session_create_response import CheckoutSessionCreateResponse
from .raw_client import AsyncRawCheckoutSessionsClient, RawCheckoutSessionsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CheckoutSessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCheckoutSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCheckoutSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCheckoutSessionsClient
        """
        return self._raw_client

    def checkout_sessions_create(
        self,
        *,
        invoice_id: typing.Optional[str] = OMIT,
        product_id: typing.Optional[str] = OMIT,
        amount_minor: typing.Optional[int] = OMIT,
        currency: typing.Optional[str] = OMIT,
        success_url: typing.Optional[str] = OMIT,
        cancel_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutSessionCreateResponse:
        """
        Create a checkout session for an invoice or product.

        Parameters
        ----------
        invoice_id : typing.Optional[str]

        product_id : typing.Optional[str]

        amount_minor : typing.Optional[int]

        currency : typing.Optional[str]

        success_url : typing.Optional[str]

        cancel_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSessionCreateResponse
            Checkout session created

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.checkout_sessions.checkout_sessions_create()
        """
        _response = self._raw_client.checkout_sessions_create(
            invoice_id=invoice_id,
            product_id=product_id,
            amount_minor=amount_minor,
            currency=currency,
            success_url=success_url,
            cancel_url=cancel_url,
            request_options=request_options,
        )
        return _response.data


class AsyncCheckoutSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCheckoutSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCheckoutSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCheckoutSessionsClient
        """
        return self._raw_client

    async def checkout_sessions_create(
        self,
        *,
        invoice_id: typing.Optional[str] = OMIT,
        product_id: typing.Optional[str] = OMIT,
        amount_minor: typing.Optional[int] = OMIT,
        currency: typing.Optional[str] = OMIT,
        success_url: typing.Optional[str] = OMIT,
        cancel_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutSessionCreateResponse:
        """
        Create a checkout session for an invoice or product.

        Parameters
        ----------
        invoice_id : typing.Optional[str]

        product_id : typing.Optional[str]

        amount_minor : typing.Optional[int]

        currency : typing.Optional[str]

        success_url : typing.Optional[str]

        cancel_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSessionCreateResponse
            Checkout session created

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout_sessions.checkout_sessions_create()


        asyncio.run(main())
        """
        _response = await self._raw_client.checkout_sessions_create(
            invoice_id=invoice_id,
            product_id=product_id,
            amount_minor=amount_minor,
            currency=currency,
            success_url=success_url,
            cancel_url=cancel_url,
            request_options=request_options,
        )
        return _response.data
