# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.refund_create_response import RefundCreateResponse
from ..types.refund_list_response import RefundListResponse
from ..types.refund_retrieve_response import RefundRetrieveResponse
from .types.create_refund_input_reason import CreateRefundInputReason
from .types.refunds_list_request_reason import RefundsListRequestReason
from .types.refunds_list_request_status import RefundsListRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawRefundsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        status: typing.Optional[RefundsListRequestStatus] = None,
        payment_id: typing.Optional[str] = None,
        gateway: typing.Optional[str] = None,
        reason: typing.Optional[RefundsListRequestReason] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RefundListResponse]:
        """
        Retrieve a paginated list of refunds with optional filters. Results are ordered by creation date (newest first).

        Parameters
        ----------
        status : typing.Optional[RefundsListRequestStatus]
            Filter by refund status

        payment_id : typing.Optional[str]
            Filter by original payment ID

        gateway : typing.Optional[str]
            Filter by payment gateway (nmi, stripe, etc.)

        reason : typing.Optional[RefundsListRequestReason]
            Filter by refund reason

        created_after : typing.Optional[str]
            ISO 8601 date - only refunds created after this date

        created_before : typing.Optional[str]
            ISO 8601 date - only refunds created before this date

        limit : typing.Optional[float]
            Number of results to return (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RefundListResponse]
            List of refunds
        """
        _response = self._client_wrapper.httpx_client.request(
            "refunds",
            method="GET",
            params={
                "status": status,
                "payment_id": payment_id,
                "gateway": gateway,
                "reason": reason,
                "created_after": created_after,
                "created_before": created_before,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefundListResponse,
                    parse_obj_as(
                        type_=RefundListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        payment_id: str,
        amount_minor: typing.Optional[float] = OMIT,
        reason: typing.Optional[CreateRefundInputReason] = OMIT,
        reason_details: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RefundCreateResponse]:
        """
        Initiate a refund for a payment. The refund will be processed through the original payment gateway.

        Parameters
        ----------
        payment_id : str
            The ID of the payment to refund

        amount_minor : typing.Optional[float]
            Amount to refund in cents. If not provided, refunds the full remaining amount.

        reason : typing.Optional[CreateRefundInputReason]
            Reason for the refund

        reason_details : typing.Optional[str]
            Additional details about the refund reason

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RefundCreateResponse]
            Refund created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "refunds",
            method="POST",
            json={
                "payment_id": payment_id,
                "amount_minor": amount_minor,
                "reason": reason,
                "reason_details": reason_details,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefundCreateResponse,
                    parse_obj_as(
                        type_=RefundCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[RefundRetrieveResponse]:
        """
        Retrieve a single refund by its public ID (ref_xxx) or internal UUID.

        Parameters
        ----------
        id : str
            Refund public ID (ref_xxx) or UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RefundRetrieveResponse]
            Refund details
        """
        _response = self._client_wrapper.httpx_client.request(
            f"refunds/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefundRetrieveResponse,
                    parse_obj_as(
                        type_=RefundRetrieveResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRefundsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        status: typing.Optional[RefundsListRequestStatus] = None,
        payment_id: typing.Optional[str] = None,
        gateway: typing.Optional[str] = None,
        reason: typing.Optional[RefundsListRequestReason] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RefundListResponse]:
        """
        Retrieve a paginated list of refunds with optional filters. Results are ordered by creation date (newest first).

        Parameters
        ----------
        status : typing.Optional[RefundsListRequestStatus]
            Filter by refund status

        payment_id : typing.Optional[str]
            Filter by original payment ID

        gateway : typing.Optional[str]
            Filter by payment gateway (nmi, stripe, etc.)

        reason : typing.Optional[RefundsListRequestReason]
            Filter by refund reason

        created_after : typing.Optional[str]
            ISO 8601 date - only refunds created after this date

        created_before : typing.Optional[str]
            ISO 8601 date - only refunds created before this date

        limit : typing.Optional[float]
            Number of results to return (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RefundListResponse]
            List of refunds
        """
        _response = await self._client_wrapper.httpx_client.request(
            "refunds",
            method="GET",
            params={
                "status": status,
                "payment_id": payment_id,
                "gateway": gateway,
                "reason": reason,
                "created_after": created_after,
                "created_before": created_before,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefundListResponse,
                    parse_obj_as(
                        type_=RefundListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        payment_id: str,
        amount_minor: typing.Optional[float] = OMIT,
        reason: typing.Optional[CreateRefundInputReason] = OMIT,
        reason_details: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RefundCreateResponse]:
        """
        Initiate a refund for a payment. The refund will be processed through the original payment gateway.

        Parameters
        ----------
        payment_id : str
            The ID of the payment to refund

        amount_minor : typing.Optional[float]
            Amount to refund in cents. If not provided, refunds the full remaining amount.

        reason : typing.Optional[CreateRefundInputReason]
            Reason for the refund

        reason_details : typing.Optional[str]
            Additional details about the refund reason

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RefundCreateResponse]
            Refund created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "refunds",
            method="POST",
            json={
                "payment_id": payment_id,
                "amount_minor": amount_minor,
                "reason": reason,
                "reason_details": reason_details,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefundCreateResponse,
                    parse_obj_as(
                        type_=RefundCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[RefundRetrieveResponse]:
        """
        Retrieve a single refund by its public ID (ref_xxx) or internal UUID.

        Parameters
        ----------
        id : str
            Refund public ID (ref_xxx) or UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RefundRetrieveResponse]
            Refund details
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"refunds/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefundRetrieveResponse,
                    parse_obj_as(
                        type_=RefundRetrieveResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
