# This file was auto-generated by Fern from our API Definition.

import typing

ChargeRetrieveResponseDataStatus = typing.Union[
    typing.Literal["pending", "processing", "succeeded", "failed", "refunded", "partially_refunded", "voided"],
    typing.Any,
]
