# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CustomerUpdateResponseData(UniversalBaseModel):
    id: str
    merchant_id: typing_extensions.Annotated[str, FieldMetadata(alias="merchantId")] = pydantic.Field(
        alias="merchantId"
    )
    merchant_ref_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="merchantRefId")] = (
        pydantic.Field(alias="merchantRefId", default=None)
    )
    email: str
    name: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    auth_user_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="authUserId")] = pydantic.Field(
        alias="authUserId", default=None
    )
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    custom_fields: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]], FieldMetadata(alias="customFields")
    ] = pydantic.Field(alias="customFields", default=None)
    """
    Custom fields
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field(
        alias="updatedAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
