# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CustomerPortalSessionCreateResponseData(UniversalBaseModel):
    id: str
    customer_id: typing_extensions.Annotated[str, FieldMetadata(alias="customerId")] = pydantic.Field(
        alias="customerId"
    )
    merchant_id: typing_extensions.Annotated[str, FieldMetadata(alias="merchantId")] = pydantic.Field(
        alias="merchantId"
    )
    url: str
    expires_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="expiresAt")] = pydantic.Field(
        alias="expiresAt"
    )
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
