# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CustomerSubscription(UniversalBaseModel):
    id: str
    customer_id: str
    price_id: typing.Optional[str] = None
    status: str
    current_period_start: typing.Optional[str] = None
    current_period_end: typing.Optional[str] = None
    cancel_at_period_end: bool
    canceled_at: typing.Optional[str] = None
    trial_end: typing.Optional[str] = None
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
