# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CustomerPayment(UniversalBaseModel):
    id: str
    customer_id: typing.Optional[str] = None
    amount_minor: int
    currency: str
    status: str
    payment_method_type: typing.Optional[str] = None
    gateway_transaction_id: typing.Optional[str] = None
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
