# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EventRequest(UniversalBaseModel):
    """
    Information about the request that triggered this event
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Request ID that triggered this event (if applicable)
    """

    idempotency_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Idempotency key used in the request (if applicable)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
