# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .invoice_subscription_terms import InvoiceSubscriptionTerms


class Invoice(UniversalBaseModel):
    id: str
    customer_uuid: str
    invoice_number: typing.Optional[str] = None
    total_minor: int
    currency: str
    status: str
    due_date: typing.Optional[str] = None
    custom_fields: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Key-value pairs for custom fields
    """

    external_source: typing.Optional[str] = pydantic.Field(default=None)
    """
    External integration source (e.g., practicehub, wodify)
    """

    external_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type within external system (e.g., appointment, membership)
    """

    external_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID from external system
    """

    subscription_terms: typing.Optional[InvoiceSubscriptionTerms] = pydantic.Field(default=None)
    """
    Subscription billing terms for recurring invoices
    """

    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
