# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_billing_type import OrderBillingType
from .order_fulfillment_status import OrderFulfillmentStatus
from .order_line_item import OrderLineItem
from .order_object import OrderObject
from .order_status import OrderStatus


class Order(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the order
    """

    object: OrderObject = pydantic.Field()
    """
    Object type
    """

    public_id: str = pydantic.Field()
    """
    Public-facing order ID
    """

    customer_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the customer
    """

    status: OrderStatus = pydantic.Field()
    """
    Order status. draft: Being built. pending: Awaiting payment. paid: Fully paid. partially_paid: Partial payment received. refunded: Refunded. canceled: Canceled. fulfilled: Shipped/delivered.
    """

    billing_type: OrderBillingType = pydantic.Field()
    """
    Billing type. one_time: Single purchase. recurring: Subscription-based.
    """

    fulfillment_status: typing.Optional[OrderFulfillmentStatus] = pydantic.Field(default=None)
    """
    Fulfillment status for physical goods.
    """

    currency: str = pydantic.Field()
    """
    Three-letter ISO currency code
    """

    subtotal: int = pydantic.Field()
    """
    Subtotal in cents
    """

    discount: int = pydantic.Field()
    """
    Total discount in cents
    """

    tax: int = pydantic.Field()
    """
    Total tax in cents
    """

    total: int = pydantic.Field()
    """
    Total amount in cents
    """

    amount_paid: int = pydantic.Field()
    """
    Amount paid in cents
    """

    amount_refunded: int = pydantic.Field()
    """
    Amount refunded in cents
    """

    amount_due: int = pydantic.Field()
    """
    Amount still due in cents
    """

    line_items: typing.Optional[typing.List[OrderLineItem]] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom key-value metadata
    """

    notes: typing.Optional[str] = None
    invoice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the linked invoice (Commercial Truth)
    """

    subscription_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the linked subscription (for recurring fulfillment)
    """

    created_at: dt.datetime
    updated_at: dt.datetime
    paid_at: typing.Optional[dt.datetime] = None
    canceled_at: typing.Optional[dt.datetime] = None
    fulfilled_at: typing.Optional[dt.datetime] = None
    expires_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
