# This file was auto-generated by Fern from our API Definition.

import typing

PaymentAttemptCategory = typing.Union[
    typing.Literal[
        "approved",
        "generic_decline",
        "insufficient_funds",
        "over_limit",
        "expired_card",
        "invalid_card_number",
        "invalid_cvv",
        "invalid_expiry",
        "invalid_pin",
        "transaction_not_allowed",
        "call_issuer",
        "incorrect_payment_info",
        "lost_or_stolen",
        "pickup_card",
        "suspected_fraud",
        "restricted_card",
        "stop_all_recurring",
        "stop_this_program",
        "update_cardholder_data",
        "processor_error",
        "gateway_error",
        "communication_error",
        "merchant_config_error",
        "merchant_inactive",
        "issuer_unavailable",
        "duplicate_transaction",
        "invalid_transaction",
        "unsupported_card",
        "feature_not_available",
        "authentication_required",
    ],
    typing.Any,
]
