# This file was auto-generated by Fern from our API Definition.

import typing

PaymentPaymentChannel = typing.Union[
    typing.Literal["card_present", "card_not_present", "bank_transfer", "manual"], typing.Any
]
