# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .product_list_response_pagination import ProductListResponsePagination


class ProductListResponse(UniversalBaseModel):
    data: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Product objects
    """

    pagination: ProductListResponsePagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
