# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionListResponseDataItemDunningPhaseSeverity = typing.Union[
    typing.Literal["info", "warning", "critical"], typing.Any
]
