# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SubscriptionPreviewRenewalResponseDataUpcomingRenewalsItem(UniversalBaseModel):
    sequence: int
    date: dt.datetime
    formatted_date: typing_extensions.Annotated[str, FieldMetadata(alias="formattedDate")] = pydantic.Field(
        alias="formattedDate"
    )
    day_name: typing_extensions.Annotated[str, FieldMetadata(alias="dayName")] = pydantic.Field(alias="dayName")
    amount_minor: typing_extensions.Annotated[int, FieldMetadata(alias="amountMinor")] = pydantic.Field(
        alias="amountMinor"
    )
    formatted_amount: typing_extensions.Annotated[str, FieldMetadata(alias="formattedAmount")] = pydantic.Field(
        alias="formattedAmount"
    )
    is_trial_end: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isTrialEnd")] = (
        pydantic.Field(alias="isTrialEnd", default=None)
    )
    is_first_charge: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isFirstCharge")] = (
        pydantic.Field(alias="isFirstCharge", default=None)
    )
    is_final_payment: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isFinalPayment")] = (
        pydantic.Field(alias="isFinalPayment", default=None)
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
