# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionTermsFirstPaymentBehavior = typing.Union[
    typing.Literal["charge_first_cycle_now", "defer_first_cycle_to_start_date"], typing.Any
]
