# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionCancelSubscriptionResponseDataStatus = typing.Union[
    typing.Literal["trialing", "active", "past_due", "paused", "canceled", "expired"], typing.Any
]
