# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .subscription_change_quantity_response_subscription import SubscriptionChangeQuantityResponseSubscription


class SubscriptionChangeQuantityResponse(UniversalBaseModel):
    subscription: SubscriptionChangeQuantityResponseSubscription
    proration: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Proration details
    """

    previous_quantity: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="previousQuantity")] = (
        pydantic.Field(alias="previousQuantity", default=None)
    )
    invoice_created: typing_extensions.Annotated[bool, FieldMetadata(alias="invoiceCreated")] = pydantic.Field(
        alias="invoiceCreated"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
