# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .schedule_phase import SchedulePhase
from .subscription_schedule_current_phase import SubscriptionScheduleCurrentPhase
from .subscription_schedule_end_behavior import SubscriptionScheduleEndBehavior
from .subscription_schedule_object import SubscriptionScheduleObject
from .subscription_schedule_status import SubscriptionScheduleStatus


class SubscriptionSchedule(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Public schedule ID (sub_sched_xxx)
    """

    object: SubscriptionScheduleObject = pydantic.Field()
    """
    Object type
    """

    status: SubscriptionScheduleStatus = pydantic.Field()
    """
    Schedule status. not_started: Scheduled for future. active: Currently executing phases. completed: All phases finished. canceled: Manually canceled. released: Detached from subscription.
    """

    customer: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer ID
    """

    subscription: typing.Optional[str] = pydantic.Field(default=None)
    """
    Linked subscription ID
    """

    current_phase: typing.Optional[SubscriptionScheduleCurrentPhase] = pydantic.Field(default=None)
    """
    Current phase being executed
    """

    phases: typing.List[SchedulePhase] = pydantic.Field()
    """
    All phases in the schedule
    """

    end_behavior: SubscriptionScheduleEndBehavior = pydantic.Field()
    """
    What happens when the schedule completes. cancel: Cancel the subscription. release: Make subscription standalone.
    """

    released_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    When released (Unix timestamp)
    """

    released_subscription: typing.Optional[str] = pydantic.Field(default=None)
    """
    Subscription ID at release time
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom metadata
    """

    created: int = pydantic.Field()
    """
    Unix timestamp of creation
    """

    livemode: bool = pydantic.Field()
    """
    Whether in live mode
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
