# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subscription_schedule import SubscriptionSchedule
from .subscription_schedule_list_response_object import SubscriptionScheduleListResponseObject


class SubscriptionScheduleListResponse(UniversalBaseModel):
    object: SubscriptionScheduleListResponseObject
    data: typing.List[SubscriptionSchedule]
    has_more: bool
    url: str = pydantic.Field()
    """
    The URL for accessing this list
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
