# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .subscription_reactivate_response_data_billing_interval import SubscriptionReactivateResponseDataBillingInterval
from .subscription_reactivate_response_data_dunning import SubscriptionReactivateResponseDataDunning
from .subscription_reactivate_response_data_status import SubscriptionReactivateResponseDataStatus


class SubscriptionReactivateResponseData(UniversalBaseModel):
    id: str
    merchant_id: typing_extensions.Annotated[str, FieldMetadata(alias="merchantId")] = pydantic.Field(
        alias="merchantId"
    )
    customer_id: typing_extensions.Annotated[str, FieldMetadata(alias="customerId")] = pydantic.Field(
        alias="customerId"
    )
    product_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="productId")] = pydantic.Field(
        alias="productId", default=None
    )
    price_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="priceId")] = pydantic.Field(
        alias="priceId", default=None
    )
    plan_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="planId")] = pydantic.Field(
        alias="planId", default=None
    )
    status: SubscriptionReactivateResponseDataStatus
    quantity: int
    amount_minor: typing_extensions.Annotated[int, FieldMetadata(alias="amountMinor")] = pydantic.Field(
        alias="amountMinor"
    )
    currency: str
    billing_interval: typing_extensions.Annotated[
        SubscriptionReactivateResponseDataBillingInterval, FieldMetadata(alias="billingInterval")
    ] = pydantic.Field(alias="billingInterval")
    current_period_start: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="currentPeriodStart")] = (
        pydantic.Field(alias="currentPeriodStart")
    )
    current_period_end: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="currentPeriodEnd")] = (
        pydantic.Field(alias="currentPeriodEnd")
    )
    trial_end: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="trialEnd")] = (
        pydantic.Field(alias="trialEnd", default=None)
    )
    canceled_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="canceledAt")] = (
        pydantic.Field(alias="canceledAt", default=None)
    )
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field(
        alias="updatedAt"
    )
    dunning: typing.Optional[SubscriptionReactivateResponseDataDunning] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
