# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tax_rate import TaxRate
from .tax_rate_list_response_object import TaxRateListResponseObject


class TaxRateListResponse(UniversalBaseModel):
    object: TaxRateListResponseObject
    data: typing.List[TaxRate]
    has_more: bool
    total_count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
