# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UsageBalanceMeter(UniversalBaseModel):
    meter_id: str = pydantic.Field()
    """
    Meter ID
    """

    meter_name: str = pydantic.Field()
    """
    Meter display name
    """

    unit_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unit display name
    """

    current_value: float = pydantic.Field()
    """
    Aggregated usage in current period
    """

    included_quantity: float = pydantic.Field()
    """
    Units included in plan (0 if pure metered)
    """

    used_quantity: float = pydantic.Field()
    """
    Usage consumed (same as current_value)
    """

    remaining_included: float = pydantic.Field()
    """
    Remaining included units (max 0)
    """

    overage_quantity: float = pydantic.Field()
    """
    Units over allowance (max 0)
    """

    estimated_amount_minor: float = pydantic.Field()
    """
    Estimated charge for overage in minor units
    """

    total_cost_minor: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sum of event cost annotations (null if no cost data)
    """

    margin_minor: typing.Optional[float] = pydantic.Field(default=None)
    """
    Estimated margin: revenue - cost (null if no cost data)
    """

    currency: str = pydantic.Field()
    """
    Currency code
    """

    period_start: str = pydantic.Field()
    """
    Current billing period start (ISO 8601)
    """

    period_end: str = pydantic.Field()
    """
    Current billing period end (ISO 8601)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
