# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .usage_balance_meter import UsageBalanceMeter
from .usage_balance_response_object import UsageBalanceResponseObject


class UsageBalanceResponse(UniversalBaseModel):
    object: UsageBalanceResponseObject
    meters: typing.List[UsageBalanceMeter]
    total_estimated_amount_minor: float = pydantic.Field()
    """
    Total estimated charge across all meters
    """

    total_cost_minor: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total cost across all meters (null if no cost data)
    """

    currency: str = pydantic.Field()
    """
    Currency code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
