# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CustomersEntitlementsListResponseDataItemBenefit(UniversalBaseModel):
    id: str
    name: str
    description: typing.Optional[str] = None
    benefit_type: typing_extensions.Annotated[str, FieldMetadata(alias="benefitType")] = pydantic.Field(
        alias="benefitType"
    )
    benefit_key: typing_extensions.Annotated[str, FieldMetadata(alias="benefitKey")] = pydantic.Field(
        alias="benefitKey"
    )
    category: typing.Optional[str] = None
    icon_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="iconUrl")] = pydantic.Field(
        alias="iconUrl", default=None
    )
    display_order: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="displayOrder")] = (
        pydantic.Field(alias="displayOrder", default=None)
    )
    is_active: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isActive")] = pydantic.Field(
        alias="isActive", default=None
    )
    default_value: typing_extensions.Annotated[typing.Optional[typing.Any], FieldMetadata(alias="defaultValue")] = (
        pydantic.Field(alias="defaultValue", default=None)
    )
    config: typing.Optional[typing.Any] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
