# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .customers_entitlements_list_response_customer import CustomersEntitlementsListResponseCustomer
from .customers_entitlements_list_response_data_item import CustomersEntitlementsListResponseDataItem
from .customers_entitlements_list_response_pagination import CustomersEntitlementsListResponsePagination


class CustomersEntitlementsListResponse(UniversalBaseModel):
    data: typing.List[CustomersEntitlementsListResponseDataItem]
    pagination: CustomersEntitlementsListResponsePagination
    customer: CustomersEntitlementsListResponseCustomer

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
