# This file was auto-generated by Fern from our API Definition.

import typing

CreateMeterPriceRequestPricingModel = typing.Union[
    typing.Literal["per_unit", "graduated", "volume", "package"], typing.Any
]
