# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionSchedulesListRequestStatus = typing.Union[
    typing.Literal["not_started", "active", "completed", "canceled", "released"], typing.Any
]
