# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.open_dispute import OpenDispute
from .disputes_get_open_response_meta import DisputesGetOpenResponseMeta


class DisputesGetOpenResponse(UniversalBaseModel):
    data: typing.List[OpenDispute]
    meta: DisputesGetOpenResponseMeta

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
