# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_finance_income_request_group_by import GetFinanceIncomeRequestGroupBy
    from .get_finance_income_response import GetFinanceIncomeResponse
    from .get_finance_income_response_summary import GetFinanceIncomeResponseSummary
    from .get_finance_summary_response import GetFinanceSummaryResponse
_dynamic_imports: typing.Dict[str, str] = {
    "GetFinanceIncomeRequestGroupBy": ".get_finance_income_request_group_by",
    "GetFinanceIncomeResponse": ".get_finance_income_response",
    "GetFinanceIncomeResponseSummary": ".get_finance_income_response_summary",
    "GetFinanceSummaryResponse": ".get_finance_summary_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetFinanceIncomeRequestGroupBy",
    "GetFinanceIncomeResponse",
    "GetFinanceIncomeResponseSummary",
    "GetFinanceSummaryResponse",
]
