# This file was auto-generated by Fern from our API Definition.

import typing

SubscriptionsChangePlanRequestProrationBehavior = typing.Union[
    typing.Literal["invoice_immediately", "next_invoice", "none"], typing.Any
]
