# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .integrations_activate_response_data_provider import IntegrationsActivateResponseDataProvider
from .integrations_activate_response_data_status import IntegrationsActivateResponseDataStatus
from .integrations_activate_response_data_sync_interval import IntegrationsActivateResponseDataSyncInterval


class IntegrationsActivateResponseData(UniversalBaseModel):
    id: str
    provider: IntegrationsActivateResponseDataProvider
    is_active: typing_extensions.Annotated[bool, FieldMetadata(alias="isActive")] = pydantic.Field(alias="isActive")
    status: typing.Optional[IntegrationsActivateResponseDataStatus] = None
    last_sync_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="lastSyncAt")] = (
        pydantic.Field(alias="lastSyncAt", default=None)
    )
    last_sync_error: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastSyncError")] = (
        pydantic.Field(alias="lastSyncError", default=None)
    )
    sync_interval: typing_extensions.Annotated[
        typing.Optional[IntegrationsActivateResponseDataSyncInterval], FieldMetadata(alias="syncInterval")
    ] = pydantic.Field(alias="syncInterval", default=None)
    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )
    updated_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="updatedAt")] = pydantic.Field(
        alias="updatedAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
