# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .integrations_get_packages_response_data_item_active import IntegrationsGetPackagesResponseDataItemActive
from .integrations_get_packages_response_data_item_id import IntegrationsGetPackagesResponseDataItemId


class IntegrationsGetPackagesResponseDataItem(UniversalBaseModel):
    id: IntegrationsGetPackagesResponseDataItemId
    name: str
    public_name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    package_type: typing.Optional[str] = None
    charge_type: typing.Optional[str] = None
    price: typing.Optional[float] = None
    visits: typing.Optional[float] = None
    active: typing.Optional[IntegrationsGetPackagesResponseDataItemActive] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
