# This file was auto-generated by Fern from our API Definition.

import typing

IntegrationsGetStatusResponseDataStatus = typing.Union[
    typing.Literal["connected", "error", "syncing", "idle"], typing.Any
]
