# This file was auto-generated by Fern from our API Definition.

import typing

IntegrationsPaymentMappingsRequestProvider = typing.Union[
    typing.Literal["practicehub", "wodify", "terminal"], typing.Any
]
