# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_payment_link_response_line_items_item_product_details_recurring_interval import (
    GetPaymentLinkResponseLineItemsItemProductDetailsRecurringInterval,
)


class GetPaymentLinkResponseLineItemsItemProductDetailsRecurring(UniversalBaseModel):
    interval: GetPaymentLinkResponseLineItemsItemProductDetailsRecurringInterval
    interval_count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
