# This file was auto-generated by Fern from our API Definition.

import typing

ListPaymentLinksResponseDataItemLineItemsItemProductDetailsRecurringInterval = typing.Union[
    typing.Literal["day", "week", "month", "year"], typing.Any
]
