# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_payment_links_response_data_item_line_items_item_product_details_recurring_interval import (
    ListPaymentLinksResponseDataItemLineItemsItemProductDetailsRecurringInterval,
)


class ListPaymentLinksResponseDataItemLineItemsItemProductDetailsRecurring(UniversalBaseModel):
    interval: ListPaymentLinksResponseDataItemLineItemsItemProductDetailsRecurringInterval
    interval_count: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
