# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.product_create_response import ProductCreateResponse
from ..types.product_list_response import ProductListResponse
from ..types.product_retrieve_response import ProductRetrieveResponse
from ..types.product_update_response import ProductUpdateResponse
from .raw_client import AsyncRawProductsClient, RawProductsClient
from .types.create_product_request_billing_anchor_rule import CreateProductRequestBillingAnchorRule
from .types.create_product_request_end_behavior import CreateProductRequestEndBehavior
from .types.create_product_request_first_charge_behavior import CreateProductRequestFirstChargeBehavior
from .types.create_product_request_fulfillment_type import CreateProductRequestFulfillmentType
from .types.create_product_request_kind import CreateProductRequestKind
from .types.create_product_request_pricing_model import CreateProductRequestPricingModel
from .types.products_external_batch_request_products_item import ProductsExternalBatchRequestProductsItem
from .types.products_external_batch_response import ProductsExternalBatchResponse
from .types.products_external_upsert_request_interval import ProductsExternalUpsertRequestInterval
from .types.products_external_upsert_request_kind import ProductsExternalUpsertRequestKind
from .types.products_external_upsert_response import ProductsExternalUpsertResponse
from .types.update_product_request_billing_anchor_rule import UpdateProductRequestBillingAnchorRule
from .types.update_product_request_end_behavior import UpdateProductRequestEndBehavior
from .types.update_product_request_first_charge_behavior import UpdateProductRequestFirstChargeBehavior
from .types.update_product_request_fulfillment_type import UpdateProductRequestFulfillmentType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProductsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProductsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProductsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProductsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductListResponse:
        """
        List products with pagination and optional search.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        search : typing.Optional[str]
            Search term to filter products

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductListResponse
            List of products

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.products.list()
        """
        _response = self._raw_client.list(page=page, limit=limit, search=search, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        product_id: str,
        name: str,
        kind: CreateProductRequestKind,
        pricing_model: CreateProductRequestPricingModel,
        amount_minor: int,
        description: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        interval: typing.Optional[str] = OMIT,
        interval_count: typing.Optional[int] = OMIT,
        trial_days: typing.Optional[int] = OMIT,
        usage_meter_id: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        fulfillment_type: typing.Optional[CreateProductRequestFulfillmentType] = OMIT,
        billing_anchor_rule: typing.Optional[CreateProductRequestBillingAnchorRule] = OMIT,
        billing_anchor_day: typing.Optional[int] = OMIT,
        first_charge_behavior: typing.Optional[CreateProductRequestFirstChargeBehavior] = OMIT,
        end_behavior: typing.Optional[CreateProductRequestEndBehavior] = OMIT,
        max_payments: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductCreateResponse:
        """
        Create a new product. Requires 'products:write' scope.

        Parameters
        ----------
        product_id : str

        name : str

        kind : CreateProductRequestKind

        pricing_model : CreateProductRequestPricingModel

        amount_minor : int

        description : typing.Optional[str]

        currency : typing.Optional[str]

        interval : typing.Optional[str]

        interval_count : typing.Optional[int]

        trial_days : typing.Optional[int]

        usage_meter_id : typing.Optional[str]

        slug : typing.Optional[str]

        fulfillment_type : typing.Optional[CreateProductRequestFulfillmentType]
            Fulfillment type for the product. Defaults to 'none' (service).

        billing_anchor_rule : typing.Optional[CreateProductRequestBillingAnchorRule]
            How billing dates are calculated. same_day: Bill on same day as start. day_of_month: Bill on specific day (1-31). last_day: Bill on last day of month.

        billing_anchor_day : typing.Optional[int]
            Day of month (1-31) when billing_anchor_rule is 'day_of_month'

        first_charge_behavior : typing.Optional[CreateProductRequestFirstChargeBehavior]
            When first payment is collected. immediate: Charge on start. next_anchor: Charge on first scheduled date. prorate: Prorate until first date.

        end_behavior : typing.Optional[CreateProductRequestEndBehavior]
            How subscription ends. until_canceled: Runs forever. fixed_payments: Ends after N billing cycles.

        max_payments : typing.Optional[int]
            Max billing cycles when end_behavior is 'fixed_payments'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductCreateResponse
            Product created successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.products.create(
            product_id="product_id",
            name="name",
            kind="subscription",
            pricing_model="one_time",
            amount_minor=1,
        )
        """
        _response = self._raw_client.create(
            product_id=product_id,
            name=name,
            kind=kind,
            pricing_model=pricing_model,
            amount_minor=amount_minor,
            description=description,
            currency=currency,
            interval=interval,
            interval_count=interval_count,
            trial_days=trial_days,
            usage_meter_id=usage_meter_id,
            slug=slug,
            fulfillment_type=fulfillment_type,
            billing_anchor_rule=billing_anchor_rule,
            billing_anchor_day=billing_anchor_day,
            first_charge_behavior=first_charge_behavior,
            end_behavior=end_behavior,
            max_payments=max_payments,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ProductRetrieveResponse:
        """
        Get a product by its ID. Requires 'products:read' scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductRetrieveResponse
            Product details

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.products.retrieve(
            id="prod_123",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        amount_minor: typing.Optional[int] = OMIT,
        currency: typing.Optional[str] = OMIT,
        interval: typing.Optional[str] = OMIT,
        interval_count: typing.Optional[int] = OMIT,
        trial_days: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        fulfillment_type: typing.Optional[UpdateProductRequestFulfillmentType] = OMIT,
        billing_anchor_rule: typing.Optional[UpdateProductRequestBillingAnchorRule] = OMIT,
        billing_anchor_day: typing.Optional[int] = OMIT,
        first_charge_behavior: typing.Optional[UpdateProductRequestFirstChargeBehavior] = OMIT,
        end_behavior: typing.Optional[UpdateProductRequestEndBehavior] = OMIT,
        max_payments: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductUpdateResponse:
        """
        Update an existing product. Requires 'products:write' scope.

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        description : typing.Optional[str]

        amount_minor : typing.Optional[int]

        currency : typing.Optional[str]

        interval : typing.Optional[str]

        interval_count : typing.Optional[int]

        trial_days : typing.Optional[int]

        is_active : typing.Optional[bool]

        is_archived : typing.Optional[bool]

        fulfillment_type : typing.Optional[UpdateProductRequestFulfillmentType]
            Fulfillment type for the product.

        billing_anchor_rule : typing.Optional[UpdateProductRequestBillingAnchorRule]
            How billing dates are calculated. same_day: Bill on same day as start. day_of_month: Bill on specific day (1-31). last_day: Bill on last day of month.

        billing_anchor_day : typing.Optional[int]

        first_charge_behavior : typing.Optional[UpdateProductRequestFirstChargeBehavior]
            When first payment is collected. immediate: Charge on start. next_anchor: Charge on first scheduled date. prorate: Prorate until first date.

        end_behavior : typing.Optional[UpdateProductRequestEndBehavior]
            How subscription ends. until_canceled: Runs forever. fixed_payments: Ends after N billing cycles.

        max_payments : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductUpdateResponse
            Product updated successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.products.update(
            id="prod_123",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            description=description,
            amount_minor=amount_minor,
            currency=currency,
            interval=interval,
            interval_count=interval_count,
            trial_days=trial_days,
            is_active=is_active,
            is_archived=is_archived,
            fulfillment_type=fulfillment_type,
            billing_anchor_rule=billing_anchor_rule,
            billing_anchor_day=billing_anchor_day,
            first_charge_behavior=first_charge_behavior,
            end_behavior=end_behavior,
            max_payments=max_payments,
            request_options=request_options,
        )
        return _response.data

    def externalupsert(
        self,
        source: str,
        external_id: str,
        *,
        name: str,
        amount_cents: int,
        merchant_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        kind: typing.Optional[ProductsExternalUpsertRequestKind] = OMIT,
        currency: typing.Optional[str] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        interval: typing.Optional[ProductsExternalUpsertRequestInterval] = OMIT,
        interval_count: typing.Optional[int] = OMIT,
        external_updated_at: typing.Optional[dt.datetime] = OMIT,
        external_ref: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductsExternalUpsertResponse:
        """
        Create or update a product by external system ID. Uses stale update protection.

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        external_id : str
            External system's product ID

        name : str
            Product name

        amount_cents : int
            Price in minor units (cents)

        merchant_id : typing.Optional[str]
            Deprecated: merchantId is derived from API key authentication. This field is ignored.

        description : typing.Optional[str]
            Product description

        kind : typing.Optional[ProductsExternalUpsertRequestKind]
            Product kind - subscription or one-time

        currency : typing.Optional[str]
            ISO 4217 currency code

        is_active : typing.Optional[bool]
            Whether the product is active

        interval : typing.Optional[ProductsExternalUpsertRequestInterval]
            Billing interval for subscriptions

        interval_count : typing.Optional[int]
            Number of intervals between billings

        external_updated_at : typing.Optional[dt.datetime]
            External system's last update timestamp for stale update protection

        external_ref : typing.Optional[str]
            Additional external reference (e.g., membership ID)

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Additional metadata from external system

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductsExternalUpsertResponse
            Product upserted successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.products.externalupsert(
            source="practicehub",
            external_id="prod_12345",
            name="Monthly Membership",
            amount_cents=9900,
        )
        """
        _response = self._raw_client.externalupsert(
            source,
            external_id,
            name=name,
            amount_cents=amount_cents,
            merchant_id=merchant_id,
            description=description,
            kind=kind,
            currency=currency,
            is_active=is_active,
            interval=interval,
            interval_count=interval_count,
            external_updated_at=external_updated_at,
            external_ref=external_ref,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def externalbatch(
        self,
        *,
        source: str,
        products: typing.Sequence[ProductsExternalBatchRequestProductsItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductsExternalBatchResponse:
        """
        Create or update multiple products by external system ID. Supports up to 100 products per request with stale update protection.

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        products : typing.Sequence[ProductsExternalBatchRequestProductsItem]
            Array of products to upsert (max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductsExternalBatchResponse
            Batch upsert completed

        Examples
        --------
        from revkeen import RevKeen
        from revkeen.products import ProductsExternalBatchRequestProductsItem

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.products.externalbatch(
            source="practicehub",
            products=[
                ProductsExternalBatchRequestProductsItem(
                    external_id="prod_12345",
                    name="Monthly Membership",
                    amount_cents=9900,
                )
            ],
        )
        """
        _response = self._raw_client.externalbatch(source=source, products=products, request_options=request_options)
        return _response.data


class AsyncProductsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProductsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProductsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProductsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductListResponse:
        """
        List products with pagination and optional search.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        search : typing.Optional[str]
            Search term to filter products

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductListResponse
            List of products

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(page=page, limit=limit, search=search, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        product_id: str,
        name: str,
        kind: CreateProductRequestKind,
        pricing_model: CreateProductRequestPricingModel,
        amount_minor: int,
        description: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        interval: typing.Optional[str] = OMIT,
        interval_count: typing.Optional[int] = OMIT,
        trial_days: typing.Optional[int] = OMIT,
        usage_meter_id: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        fulfillment_type: typing.Optional[CreateProductRequestFulfillmentType] = OMIT,
        billing_anchor_rule: typing.Optional[CreateProductRequestBillingAnchorRule] = OMIT,
        billing_anchor_day: typing.Optional[int] = OMIT,
        first_charge_behavior: typing.Optional[CreateProductRequestFirstChargeBehavior] = OMIT,
        end_behavior: typing.Optional[CreateProductRequestEndBehavior] = OMIT,
        max_payments: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductCreateResponse:
        """
        Create a new product. Requires 'products:write' scope.

        Parameters
        ----------
        product_id : str

        name : str

        kind : CreateProductRequestKind

        pricing_model : CreateProductRequestPricingModel

        amount_minor : int

        description : typing.Optional[str]

        currency : typing.Optional[str]

        interval : typing.Optional[str]

        interval_count : typing.Optional[int]

        trial_days : typing.Optional[int]

        usage_meter_id : typing.Optional[str]

        slug : typing.Optional[str]

        fulfillment_type : typing.Optional[CreateProductRequestFulfillmentType]
            Fulfillment type for the product. Defaults to 'none' (service).

        billing_anchor_rule : typing.Optional[CreateProductRequestBillingAnchorRule]
            How billing dates are calculated. same_day: Bill on same day as start. day_of_month: Bill on specific day (1-31). last_day: Bill on last day of month.

        billing_anchor_day : typing.Optional[int]
            Day of month (1-31) when billing_anchor_rule is 'day_of_month'

        first_charge_behavior : typing.Optional[CreateProductRequestFirstChargeBehavior]
            When first payment is collected. immediate: Charge on start. next_anchor: Charge on first scheduled date. prorate: Prorate until first date.

        end_behavior : typing.Optional[CreateProductRequestEndBehavior]
            How subscription ends. until_canceled: Runs forever. fixed_payments: Ends after N billing cycles.

        max_payments : typing.Optional[int]
            Max billing cycles when end_behavior is 'fixed_payments'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductCreateResponse
            Product created successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.create(
                product_id="product_id",
                name="name",
                kind="subscription",
                pricing_model="one_time",
                amount_minor=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            product_id=product_id,
            name=name,
            kind=kind,
            pricing_model=pricing_model,
            amount_minor=amount_minor,
            description=description,
            currency=currency,
            interval=interval,
            interval_count=interval_count,
            trial_days=trial_days,
            usage_meter_id=usage_meter_id,
            slug=slug,
            fulfillment_type=fulfillment_type,
            billing_anchor_rule=billing_anchor_rule,
            billing_anchor_day=billing_anchor_day,
            first_charge_behavior=first_charge_behavior,
            end_behavior=end_behavior,
            max_payments=max_payments,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProductRetrieveResponse:
        """
        Get a product by its ID. Requires 'products:read' scope.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductRetrieveResponse
            Product details

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.retrieve(
                id="prod_123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        amount_minor: typing.Optional[int] = OMIT,
        currency: typing.Optional[str] = OMIT,
        interval: typing.Optional[str] = OMIT,
        interval_count: typing.Optional[int] = OMIT,
        trial_days: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        fulfillment_type: typing.Optional[UpdateProductRequestFulfillmentType] = OMIT,
        billing_anchor_rule: typing.Optional[UpdateProductRequestBillingAnchorRule] = OMIT,
        billing_anchor_day: typing.Optional[int] = OMIT,
        first_charge_behavior: typing.Optional[UpdateProductRequestFirstChargeBehavior] = OMIT,
        end_behavior: typing.Optional[UpdateProductRequestEndBehavior] = OMIT,
        max_payments: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductUpdateResponse:
        """
        Update an existing product. Requires 'products:write' scope.

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        description : typing.Optional[str]

        amount_minor : typing.Optional[int]

        currency : typing.Optional[str]

        interval : typing.Optional[str]

        interval_count : typing.Optional[int]

        trial_days : typing.Optional[int]

        is_active : typing.Optional[bool]

        is_archived : typing.Optional[bool]

        fulfillment_type : typing.Optional[UpdateProductRequestFulfillmentType]
            Fulfillment type for the product.

        billing_anchor_rule : typing.Optional[UpdateProductRequestBillingAnchorRule]
            How billing dates are calculated. same_day: Bill on same day as start. day_of_month: Bill on specific day (1-31). last_day: Bill on last day of month.

        billing_anchor_day : typing.Optional[int]

        first_charge_behavior : typing.Optional[UpdateProductRequestFirstChargeBehavior]
            When first payment is collected. immediate: Charge on start. next_anchor: Charge on first scheduled date. prorate: Prorate until first date.

        end_behavior : typing.Optional[UpdateProductRequestEndBehavior]
            How subscription ends. until_canceled: Runs forever. fixed_payments: Ends after N billing cycles.

        max_payments : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductUpdateResponse
            Product updated successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.update(
                id="prod_123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            description=description,
            amount_minor=amount_minor,
            currency=currency,
            interval=interval,
            interval_count=interval_count,
            trial_days=trial_days,
            is_active=is_active,
            is_archived=is_archived,
            fulfillment_type=fulfillment_type,
            billing_anchor_rule=billing_anchor_rule,
            billing_anchor_day=billing_anchor_day,
            first_charge_behavior=first_charge_behavior,
            end_behavior=end_behavior,
            max_payments=max_payments,
            request_options=request_options,
        )
        return _response.data

    async def externalupsert(
        self,
        source: str,
        external_id: str,
        *,
        name: str,
        amount_cents: int,
        merchant_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        kind: typing.Optional[ProductsExternalUpsertRequestKind] = OMIT,
        currency: typing.Optional[str] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        interval: typing.Optional[ProductsExternalUpsertRequestInterval] = OMIT,
        interval_count: typing.Optional[int] = OMIT,
        external_updated_at: typing.Optional[dt.datetime] = OMIT,
        external_ref: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductsExternalUpsertResponse:
        """
        Create or update a product by external system ID. Uses stale update protection.

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        external_id : str
            External system's product ID

        name : str
            Product name

        amount_cents : int
            Price in minor units (cents)

        merchant_id : typing.Optional[str]
            Deprecated: merchantId is derived from API key authentication. This field is ignored.

        description : typing.Optional[str]
            Product description

        kind : typing.Optional[ProductsExternalUpsertRequestKind]
            Product kind - subscription or one-time

        currency : typing.Optional[str]
            ISO 4217 currency code

        is_active : typing.Optional[bool]
            Whether the product is active

        interval : typing.Optional[ProductsExternalUpsertRequestInterval]
            Billing interval for subscriptions

        interval_count : typing.Optional[int]
            Number of intervals between billings

        external_updated_at : typing.Optional[dt.datetime]
            External system's last update timestamp for stale update protection

        external_ref : typing.Optional[str]
            Additional external reference (e.g., membership ID)

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Additional metadata from external system

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductsExternalUpsertResponse
            Product upserted successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.externalupsert(
                source="practicehub",
                external_id="prod_12345",
                name="Monthly Membership",
                amount_cents=9900,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.externalupsert(
            source,
            external_id,
            name=name,
            amount_cents=amount_cents,
            merchant_id=merchant_id,
            description=description,
            kind=kind,
            currency=currency,
            is_active=is_active,
            interval=interval,
            interval_count=interval_count,
            external_updated_at=external_updated_at,
            external_ref=external_ref,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def externalbatch(
        self,
        *,
        source: str,
        products: typing.Sequence[ProductsExternalBatchRequestProductsItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductsExternalBatchResponse:
        """
        Create or update multiple products by external system ID. Supports up to 100 products per request with stale update protection.

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        products : typing.Sequence[ProductsExternalBatchRequestProductsItem]
            Array of products to upsert (max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductsExternalBatchResponse
            Batch upsert completed

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen
        from revkeen.products import ProductsExternalBatchRequestProductsItem

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.externalbatch(
                source="practicehub",
                products=[
                    ProductsExternalBatchRequestProductsItem(
                        external_id="prod_12345",
                        name="Monthly Membership",
                        amount_cents=9900,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.externalbatch(
            source=source, products=products, request_options=request_options
        )
        return _response.data
