# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_price_request_interval import CreatePriceRequestInterval
    from .create_price_request_pricing_model import CreatePriceRequestPricingModel
    from .create_price_request_type import CreatePriceRequestType
    from .prices_list_request_active import PricesListRequestActive
    from .prices_list_request_pricing_model import PricesListRequestPricingModel
    from .prices_list_request_type import PricesListRequestType
_dynamic_imports: typing.Dict[str, str] = {
    "CreatePriceRequestInterval": ".create_price_request_interval",
    "CreatePriceRequestPricingModel": ".create_price_request_pricing_model",
    "CreatePriceRequestType": ".create_price_request_type",
    "PricesListRequestActive": ".prices_list_request_active",
    "PricesListRequestPricingModel": ".prices_list_request_pricing_model",
    "PricesListRequestType": ".prices_list_request_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreatePriceRequestInterval",
    "CreatePriceRequestPricingModel",
    "CreatePriceRequestType",
    "PricesListRequestActive",
    "PricesListRequestPricingModel",
    "PricesListRequestType",
]
