# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.schedule_phase import SchedulePhase
from ..types.subscription_schedule import SubscriptionSchedule
from ..types.subscription_schedule_list_response import SubscriptionScheduleListResponse
from .raw_client import AsyncRawSubscriptionSchedulesClient, RawSubscriptionSchedulesClient
from .types.create_subscription_schedule_request_end_behavior import CreateSubscriptionScheduleRequestEndBehavior
from .types.create_subscription_schedule_request_start_date import CreateSubscriptionScheduleRequestStartDate
from .types.subscription_schedules_list_request_status import SubscriptionSchedulesListRequestStatus
from .types.update_subscription_schedule_request_end_behavior import UpdateSubscriptionScheduleRequestEndBehavior
from .types.update_subscription_schedule_request_proration_behavior import (
    UpdateSubscriptionScheduleRequestProrationBehavior,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubscriptionSchedulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubscriptionSchedulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubscriptionSchedulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubscriptionSchedulesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        customer: typing.Optional[str] = None,
        subscription: typing.Optional[str] = None,
        status: typing.Optional[SubscriptionSchedulesListRequestStatus] = None,
        scheduled_gte: typing.Optional[float] = None,
        scheduled_lte: typing.Optional[float] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionScheduleListResponse:
        """
        Returns a list of subscription schedules with optional filters.

        Parameters
        ----------
        customer : typing.Optional[str]
            Filter by customer ID

        subscription : typing.Optional[str]
            Filter by subscription ID

        status : typing.Optional[SubscriptionSchedulesListRequestStatus]
            Filter by status

        scheduled_gte : typing.Optional[float]
            Start date >= (Unix timestamp)

        scheduled_lte : typing.Optional[float]
            Start date <= (Unix timestamp)

        limit : typing.Optional[int]
            Max results (1-100)

        starting_after : typing.Optional[str]
            Cursor - return results after this ID

        ending_before : typing.Optional[str]
            Cursor - return results before this ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionScheduleListResponse
            List of schedules

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.subscription_schedules.list()
        """
        _response = self._raw_client.list(
            customer=customer,
            subscription=subscription,
            status=status,
            scheduled_gte=scheduled_gte,
            scheduled_lte=scheduled_lte,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        *,
        phases: typing.Sequence[SchedulePhase],
        customer: typing.Optional[str] = OMIT,
        subscription: typing.Optional[str] = OMIT,
        start_date: typing.Optional[CreateSubscriptionScheduleRequestStartDate] = OMIT,
        end_behavior: typing.Optional[CreateSubscriptionScheduleRequestEndBehavior] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Creates a subscription schedule to manage future subscription changes. Schedules define phases with different pricing/plans that transition automatically.

        Parameters
        ----------
        phases : typing.Sequence[SchedulePhase]
            Phases defining the schedule (at least one required)

        customer : typing.Optional[str]
            Customer ID (required if no subscription)

        subscription : typing.Optional[str]
            Existing subscription to attach schedule to

        start_date : typing.Optional[CreateSubscriptionScheduleRequestStartDate]
            When schedule starts. 'now', ISO date, or Unix timestamp. Defaults to now.

        end_behavior : typing.Optional[CreateSubscriptionScheduleRequestEndBehavior]
            What happens when all phases complete

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule created successfully

        Examples
        --------
        from revkeen import PhaseItem, RevKeen, SchedulePhase

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.subscription_schedules.create(
            phases=[
                SchedulePhase(
                    items=[
                        PhaseItem(
                            price_id="price_id",
                        )
                    ],
                    start_date="2026-03-01T00:00:00Z",
                )
            ],
        )
        """
        _response = self._raw_client.create(
            phases=phases,
            customer=customer,
            subscription=subscription,
            start_date=start_date,
            end_behavior=end_behavior,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SubscriptionSchedule:
        """
        Retrieves a subscription schedule by its ID.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule details

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.subscription_schedules.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        phases: typing.Optional[typing.Sequence[SchedulePhase]] = OMIT,
        end_behavior: typing.Optional[UpdateSubscriptionScheduleRequestEndBehavior] = OMIT,
        proration_behavior: typing.Optional[UpdateSubscriptionScheduleRequestProrationBehavior] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Updates a subscription schedule. Only schedules in 'not_started' or 'active' status can be updated.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        phases : typing.Optional[typing.Sequence[SchedulePhase]]
            Replace all phases

        end_behavior : typing.Optional[UpdateSubscriptionScheduleRequestEndBehavior]
            What happens when all phases complete

        proration_behavior : typing.Optional[UpdateSubscriptionScheduleRequestProrationBehavior]
            Proration behavior when updating phases

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule updated

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.subscription_schedules.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            phases=phases,
            end_behavior=end_behavior,
            proration_behavior=proration_behavior,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def cancel(
        self,
        id: str,
        *,
        invoice_now: typing.Optional[bool] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Cancels a subscription schedule. Only schedules in 'not_started' or 'active' status can be canceled.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        invoice_now : typing.Optional[bool]
            Generate a final invoice immediately

        prorate : typing.Optional[bool]
            Prorate final invoice

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule canceled

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.subscription_schedules.cancel(
            id="id",
        )
        """
        _response = self._raw_client.cancel(
            id, invoice_now=invoice_now, prorate=prorate, request_options=request_options
        )
        return _response.data

    def release(
        self,
        id: str,
        *,
        preserve_cancel_date: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Releases a subscription schedule, detaching it from the subscription. The subscription becomes standalone and continues normally.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        preserve_cancel_date : typing.Optional[bool]
            Keep the subscription's cancel_at date if set

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule released

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.subscription_schedules.release(
            id="id",
        )
        """
        _response = self._raw_client.release(
            id, preserve_cancel_date=preserve_cancel_date, request_options=request_options
        )
        return _response.data


class AsyncSubscriptionSchedulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubscriptionSchedulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubscriptionSchedulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubscriptionSchedulesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        customer: typing.Optional[str] = None,
        subscription: typing.Optional[str] = None,
        status: typing.Optional[SubscriptionSchedulesListRequestStatus] = None,
        scheduled_gte: typing.Optional[float] = None,
        scheduled_lte: typing.Optional[float] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionScheduleListResponse:
        """
        Returns a list of subscription schedules with optional filters.

        Parameters
        ----------
        customer : typing.Optional[str]
            Filter by customer ID

        subscription : typing.Optional[str]
            Filter by subscription ID

        status : typing.Optional[SubscriptionSchedulesListRequestStatus]
            Filter by status

        scheduled_gte : typing.Optional[float]
            Start date >= (Unix timestamp)

        scheduled_lte : typing.Optional[float]
            Start date <= (Unix timestamp)

        limit : typing.Optional[int]
            Max results (1-100)

        starting_after : typing.Optional[str]
            Cursor - return results after this ID

        ending_before : typing.Optional[str]
            Cursor - return results before this ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionScheduleListResponse
            List of schedules

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subscription_schedules.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            customer=customer,
            subscription=subscription,
            status=status,
            scheduled_gte=scheduled_gte,
            scheduled_lte=scheduled_lte,
            limit=limit,
            starting_after=starting_after,
            ending_before=ending_before,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        *,
        phases: typing.Sequence[SchedulePhase],
        customer: typing.Optional[str] = OMIT,
        subscription: typing.Optional[str] = OMIT,
        start_date: typing.Optional[CreateSubscriptionScheduleRequestStartDate] = OMIT,
        end_behavior: typing.Optional[CreateSubscriptionScheduleRequestEndBehavior] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Creates a subscription schedule to manage future subscription changes. Schedules define phases with different pricing/plans that transition automatically.

        Parameters
        ----------
        phases : typing.Sequence[SchedulePhase]
            Phases defining the schedule (at least one required)

        customer : typing.Optional[str]
            Customer ID (required if no subscription)

        subscription : typing.Optional[str]
            Existing subscription to attach schedule to

        start_date : typing.Optional[CreateSubscriptionScheduleRequestStartDate]
            When schedule starts. 'now', ISO date, or Unix timestamp. Defaults to now.

        end_behavior : typing.Optional[CreateSubscriptionScheduleRequestEndBehavior]
            What happens when all phases complete

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule created successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen, PhaseItem, SchedulePhase

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subscription_schedules.create(
                phases=[
                    SchedulePhase(
                        items=[
                            PhaseItem(
                                price_id="price_id",
                            )
                        ],
                        start_date="2026-03-01T00:00:00Z",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            phases=phases,
            customer=customer,
            subscription=subscription,
            start_date=start_date,
            end_behavior=end_behavior,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionSchedule:
        """
        Retrieves a subscription schedule by its ID.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule details

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subscription_schedules.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        phases: typing.Optional[typing.Sequence[SchedulePhase]] = OMIT,
        end_behavior: typing.Optional[UpdateSubscriptionScheduleRequestEndBehavior] = OMIT,
        proration_behavior: typing.Optional[UpdateSubscriptionScheduleRequestProrationBehavior] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Updates a subscription schedule. Only schedules in 'not_started' or 'active' status can be updated.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        phases : typing.Optional[typing.Sequence[SchedulePhase]]
            Replace all phases

        end_behavior : typing.Optional[UpdateSubscriptionScheduleRequestEndBehavior]
            What happens when all phases complete

        proration_behavior : typing.Optional[UpdateSubscriptionScheduleRequestProrationBehavior]
            Proration behavior when updating phases

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule updated

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subscription_schedules.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            phases=phases,
            end_behavior=end_behavior,
            proration_behavior=proration_behavior,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def cancel(
        self,
        id: str,
        *,
        invoice_now: typing.Optional[bool] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Cancels a subscription schedule. Only schedules in 'not_started' or 'active' status can be canceled.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        invoice_now : typing.Optional[bool]
            Generate a final invoice immediately

        prorate : typing.Optional[bool]
            Prorate final invoice

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule canceled

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subscription_schedules.cancel(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(
            id, invoice_now=invoice_now, prorate=prorate, request_options=request_options
        )
        return _response.data

    async def release(
        self,
        id: str,
        *,
        preserve_cancel_date: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubscriptionSchedule:
        """
        Releases a subscription schedule, detaching it from the subscription. The subscription becomes standalone and continues normally.

        Parameters
        ----------
        id : str
            Schedule ID (sub_sched_xxx or UUID)

        preserve_cancel_date : typing.Optional[bool]
            Keep the subscription's cancel_at date if set

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionSchedule
            Schedule released

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.subscription_schedules.release(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.release(
            id, preserve_cancel_date=preserve_cancel_date, request_options=request_options
        )
        return _response.data
