# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.forbidden_error import ForbiddenError
from ..errors.unauthorized_error import UnauthorizedError
from .types.sync_state_list_response import SyncStateListResponse
from .types.sync_state_update_request_last_sync_status import SyncStateUpdateRequestLastSyncStatus
from .types.sync_state_update_response import SyncStateUpdateResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSyncStateClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def sync_state_list(
        self, source: str, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SyncStateListResponse]:
        """
        Get all sync states for a specific integration (by provider and merchant).

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        merchant_id : str
            Merchant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SyncStateListResponse]
            List of sync states by resource type
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sync-state/{jsonable_encoder(source)}/{jsonable_encoder(merchant_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SyncStateListResponse,
                    parse_obj_as(
                        type_=SyncStateListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def sync_state_update(
        self,
        source: str,
        merchant_id: str,
        resource_type: str,
        *,
        last_sync_at: typing.Optional[dt.datetime] = OMIT,
        last_sync_status: typing.Optional[SyncStateUpdateRequestLastSyncStatus] = OMIT,
        last_sync_error: typing.Optional[str] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        items_synced: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SyncStateUpdateResponse]:
        """
        Update or create sync state for a specific resource type. Used by worker after sync jobs.

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        merchant_id : str
            Merchant ID

        resource_type : str
            Resource type (e.g., members, products, payments)

        last_sync_at : typing.Optional[dt.datetime]

        last_sync_status : typing.Optional[SyncStateUpdateRequestLastSyncStatus]

        last_sync_error : typing.Optional[str]

        cursor : typing.Optional[str]

        items_synced : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SyncStateUpdateResponse]
            Sync state updated/created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sync-state/{jsonable_encoder(source)}/{jsonable_encoder(merchant_id)}/{jsonable_encoder(resource_type)}",
            method="PUT",
            json={
                "lastSyncAt": last_sync_at,
                "lastSyncStatus": last_sync_status,
                "lastSyncError": last_sync_error,
                "cursor": cursor,
                "itemsSynced": items_synced,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SyncStateUpdateResponse,
                    parse_obj_as(
                        type_=SyncStateUpdateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSyncStateClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def sync_state_list(
        self, source: str, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SyncStateListResponse]:
        """
        Get all sync states for a specific integration (by provider and merchant).

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        merchant_id : str
            Merchant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SyncStateListResponse]
            List of sync states by resource type
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sync-state/{jsonable_encoder(source)}/{jsonable_encoder(merchant_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SyncStateListResponse,
                    parse_obj_as(
                        type_=SyncStateListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def sync_state_update(
        self,
        source: str,
        merchant_id: str,
        resource_type: str,
        *,
        last_sync_at: typing.Optional[dt.datetime] = OMIT,
        last_sync_status: typing.Optional[SyncStateUpdateRequestLastSyncStatus] = OMIT,
        last_sync_error: typing.Optional[str] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        items_synced: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SyncStateUpdateResponse]:
        """
        Update or create sync state for a specific resource type. Used by worker after sync jobs.

        Parameters
        ----------
        source : str
            Integration source (e.g., practicehub, wodify)

        merchant_id : str
            Merchant ID

        resource_type : str
            Resource type (e.g., members, products, payments)

        last_sync_at : typing.Optional[dt.datetime]

        last_sync_status : typing.Optional[SyncStateUpdateRequestLastSyncStatus]

        last_sync_error : typing.Optional[str]

        cursor : typing.Optional[str]

        items_synced : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SyncStateUpdateResponse]
            Sync state updated/created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sync-state/{jsonable_encoder(source)}/{jsonable_encoder(merchant_id)}/{jsonable_encoder(resource_type)}",
            method="PUT",
            json={
                "lastSyncAt": last_sync_at,
                "lastSyncStatus": last_sync_status,
                "lastSyncError": last_sync_error,
                "cursor": cursor,
                "itemsSynced": items_synced,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SyncStateUpdateResponse,
                    parse_obj_as(
                        type_=SyncStateUpdateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
