# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .delete_user_invitations_id_response import DeleteUserInvitationsIdResponse
    from .get_user_invitations_response import GetUserInvitationsResponse
    from .get_user_invitations_response_data_item import GetUserInvitationsResponseDataItem
    from .get_user_invitations_response_data_item_role import GetUserInvitationsResponseDataItemRole
    from .post_user_invitations_accept_response import PostUserInvitationsAcceptResponse
    from .post_user_invitations_id_resend_response import PostUserInvitationsIdResendResponse
    from .post_user_invitations_id_resend_response_data import PostUserInvitationsIdResendResponseData
    from .post_user_invitations_id_resend_response_data_role import PostUserInvitationsIdResendResponseDataRole
    from .post_user_invitations_request_role import PostUserInvitationsRequestRole
    from .post_user_invitations_response import PostUserInvitationsResponse
    from .post_user_invitations_response_data import PostUserInvitationsResponseData
    from .post_user_invitations_response_data_role import PostUserInvitationsResponseDataRole
_dynamic_imports: typing.Dict[str, str] = {
    "DeleteUserInvitationsIdResponse": ".delete_user_invitations_id_response",
    "GetUserInvitationsResponse": ".get_user_invitations_response",
    "GetUserInvitationsResponseDataItem": ".get_user_invitations_response_data_item",
    "GetUserInvitationsResponseDataItemRole": ".get_user_invitations_response_data_item_role",
    "PostUserInvitationsAcceptResponse": ".post_user_invitations_accept_response",
    "PostUserInvitationsIdResendResponse": ".post_user_invitations_id_resend_response",
    "PostUserInvitationsIdResendResponseData": ".post_user_invitations_id_resend_response_data",
    "PostUserInvitationsIdResendResponseDataRole": ".post_user_invitations_id_resend_response_data_role",
    "PostUserInvitationsRequestRole": ".post_user_invitations_request_role",
    "PostUserInvitationsResponse": ".post_user_invitations_response",
    "PostUserInvitationsResponseData": ".post_user_invitations_response_data",
    "PostUserInvitationsResponseDataRole": ".post_user_invitations_response_data_role",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DeleteUserInvitationsIdResponse",
    "GetUserInvitationsResponse",
    "GetUserInvitationsResponseDataItem",
    "GetUserInvitationsResponseDataItemRole",
    "PostUserInvitationsAcceptResponse",
    "PostUserInvitationsIdResendResponse",
    "PostUserInvitationsIdResendResponseData",
    "PostUserInvitationsIdResendResponseDataRole",
    "PostUserInvitationsRequestRole",
    "PostUserInvitationsResponse",
    "PostUserInvitationsResponseData",
    "PostUserInvitationsResponseDataRole",
]
