# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAppsClient, RawAppsClient
from .types.delete_apps_app_key_install_response import DeleteAppsAppKeyInstallResponse
from .types.get_apps_entitlements_response import GetAppsEntitlementsResponse
from .types.post_apps_app_key_install_response import PostAppsAppKeyInstallResponse


class AppsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAppsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAppsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAppsClient
        """
        return self._raw_client

    def install_an_app(
        self, app_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostAppsAppKeyInstallResponse:
        """
        Install an app for the authenticated tenant. Requires 'apps:write' scope.

        Parameters
        ----------
        app_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAppsAppKeyInstallResponse
            App installed successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.apps.install_an_app(
            app_key="quaderno",
        )
        """
        _response = self._raw_client.install_an_app(app_key, request_options=request_options)
        return _response.data

    def uninstall_an_app(
        self, app_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteAppsAppKeyInstallResponse:
        """
        Uninstall an app for the authenticated tenant. Requires 'apps:write' scope.

        Parameters
        ----------
        app_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAppsAppKeyInstallResponse
            App uninstalled successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.apps.uninstall_an_app(
            app_key="quaderno",
        )
        """
        _response = self._raw_client.uninstall_an_app(app_key, request_options=request_options)
        return _response.data

    def get_entitlements(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAppsEntitlementsResponse:
        """
        Get entitlements for the authenticated tenant. Requires 'apps:read' scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAppsEntitlementsResponse
            Entitlements retrieved successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.apps.get_entitlements()
        """
        _response = self._raw_client.get_entitlements(request_options=request_options)
        return _response.data


class AsyncAppsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAppsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAppsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAppsClient
        """
        return self._raw_client

    async def install_an_app(
        self, app_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostAppsAppKeyInstallResponse:
        """
        Install an app for the authenticated tenant. Requires 'apps:write' scope.

        Parameters
        ----------
        app_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAppsAppKeyInstallResponse
            App installed successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.apps.install_an_app(
                app_key="quaderno",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.install_an_app(app_key, request_options=request_options)
        return _response.data

    async def uninstall_an_app(
        self, app_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteAppsAppKeyInstallResponse:
        """
        Uninstall an app for the authenticated tenant. Requires 'apps:write' scope.

        Parameters
        ----------
        app_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAppsAppKeyInstallResponse
            App uninstalled successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.apps.uninstall_an_app(
                app_key="quaderno",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.uninstall_an_app(app_key, request_options=request_options)
        return _response.data

    async def get_entitlements(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAppsEntitlementsResponse:
        """
        Get entitlements for the authenticated tenant. Requires 'apps:read' scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAppsEntitlementsResponse
            Entitlements retrieved successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.apps.get_entitlements()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_entitlements(request_options=request_options)
        return _response.data
