# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.terminal_payment_list_response import TerminalPaymentListResponse
from ..types.terminal_payment_response import TerminalPaymentResponse
from .raw_client import AsyncRawTerminalPaymentsClient, RawTerminalPaymentsClient
from .types.list_terminal_payments_request_status import ListTerminalPaymentsRequestStatus
from .types.list_terminal_payments_request_type import ListTerminalPaymentsRequestType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TerminalPaymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTerminalPaymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTerminalPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTerminalPaymentsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        invoice_id: typing.Optional[str] = None,
        status: typing.Optional[ListTerminalPaymentsRequestStatus] = None,
        type: typing.Optional[ListTerminalPaymentsRequestType] = None,
        device_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TerminalPaymentListResponse:
        """
        List terminal payment attempts for the authenticated merchant. Supports filtering by invoice, status, type, and device. Uses cursor-based pagination.

        Parameters
        ----------
        invoice_id : typing.Optional[str]
            Filter by invoice ID

        status : typing.Optional[ListTerminalPaymentsRequestStatus]
            Filter by payment status

        type : typing.Optional[ListTerminalPaymentsRequestType]
            Filter by payment type

        device_id : typing.Optional[str]
            Filter by device ID

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        starting_after : typing.Optional[str]
            Cursor for pagination — return results after this terminal payment ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentListResponse
            List of terminal payments

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.terminal_payments.list()
        """
        _response = self._raw_client.list(
            invoice_id=invoice_id,
            status=status,
            type=type,
            device_id=device_id,
            limit=limit,
            starting_after=starting_after,
            request_options=request_options,
        )
        return _response.data

    def create(
        self,
        *,
        device_id: str,
        amount_minor: int,
        currency: str,
        invoice_id: typing.Optional[str] = OMIT,
        reference: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TerminalPaymentResponse:
        """
        Send a card-present payment request to a specific terminal device. The payment is dispatched to the merchant's POS connector which forwards it to the PAX terminal.

        **Device Selection:** You must provide a `device_id`. Use [List Terminal Devices](#tag/Terminal-Devices/operation/terminal_devices_list) to discover available devices and their IDs. Even merchants with a single terminal must pass the `device_id` explicitly — there is no auto-routing fallback.

        **Invoice Association:** `invoice_id` is optional. Omit it for walk-in or ad-hoc payments where no pre-existing invoice exists.

        The response returns immediately with status `requested`. Subscribe to terminal webhooks (`billing.terminal_payment.succeeded`, `billing.terminal_payment.declined`, etc.) to receive the outcome asynchronously.

        Parameters
        ----------
        device_id : str
            The ID of the terminal device to send the payment to. Use List Devices to discover available device IDs. Even merchants with a single terminal must pass the device_id explicitly — there is no auto-routing fallback.

        amount_minor : int
            Amount in minor units (e.g., pence for GBP, cents for USD)

        currency : str
            ISO 4217 currency code

        invoice_id : typing.Optional[str]
            The invoice to charge. Omit for walk-in or ad-hoc payments where no invoice exists. When omitted, the terminal payment is recorded without an invoice association.

        reference : typing.Optional[str]
            Custom reference for the payment. Auto-generated if not provided.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Payment dispatched to terminal

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.terminal_payments.create(
            device_id="d1e2f3a4-b5c6-7890-abcd-ef1234567890",
            amount_minor=5000,
            currency="GBP",
        )
        """
        _response = self._raw_client.create(
            device_id=device_id,
            amount_minor=amount_minor,
            currency=currency,
            invoice_id=invoice_id,
            reference=reference,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TerminalPaymentResponse:
        """
        Get a terminal payment attempt by ID.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Terminal payment details

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.terminal_payments.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TerminalPaymentResponse:
        """
        Cancel an in-progress terminal payment. Only payments with status `requested` or `in_progress` can be cancelled.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Payment cancelled

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.terminal_payments.cancel(
            id="id",
        )
        """
        _response = self._raw_client.cancel(id, request_options=request_options)
        return _response.data

    def refund(
        self,
        id: str,
        *,
        amount_minor: typing.Optional[int] = OMIT,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TerminalPaymentResponse:
        """
        Initiate a refund for a completed terminal payment. The refund is sent to the same terminal that processed the original sale.

        `amount_minor` is optional — omit for a full refund. For partial refunds, specify the amount in minor units.

        The refund command is dispatched asynchronously. Subscribe to `billing.terminal_refund.succeeded` webhooks for the outcome.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID of the original sale

        amount_minor : typing.Optional[int]
            Amount to refund in minor units. Omit for a full refund.

        reason : typing.Optional[str]
            Reason for the refund

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Refund dispatched to terminal

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.terminal_payments.refund(
            id="id",
        )
        """
        _response = self._raw_client.refund(
            id, amount_minor=amount_minor, reason=reason, request_options=request_options
        )
        return _response.data

    def void(
        self, id: str, *, reason: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> TerminalPaymentResponse:
        """
        Void a completed terminal payment. Voids are always for the full amount — partial voids are not supported. The void is sent to the same terminal that processed the original sale.

        Voids are only possible for unsettled transactions. If the transaction has already settled, use a refund instead.

        The void command is dispatched asynchronously. Subscribe to `billing.terminal_void.succeeded` webhooks for the outcome.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID of the original sale

        reason : typing.Optional[str]
            Reason for the void

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Void dispatched to terminal

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.terminal_payments.void(
            id="id",
        )
        """
        _response = self._raw_client.void(id, reason=reason, request_options=request_options)
        return _response.data


class AsyncTerminalPaymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTerminalPaymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTerminalPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTerminalPaymentsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        invoice_id: typing.Optional[str] = None,
        status: typing.Optional[ListTerminalPaymentsRequestStatus] = None,
        type: typing.Optional[ListTerminalPaymentsRequestType] = None,
        device_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TerminalPaymentListResponse:
        """
        List terminal payment attempts for the authenticated merchant. Supports filtering by invoice, status, type, and device. Uses cursor-based pagination.

        Parameters
        ----------
        invoice_id : typing.Optional[str]
            Filter by invoice ID

        status : typing.Optional[ListTerminalPaymentsRequestStatus]
            Filter by payment status

        type : typing.Optional[ListTerminalPaymentsRequestType]
            Filter by payment type

        device_id : typing.Optional[str]
            Filter by device ID

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        starting_after : typing.Optional[str]
            Cursor for pagination — return results after this terminal payment ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentListResponse
            List of terminal payments

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.terminal_payments.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            invoice_id=invoice_id,
            status=status,
            type=type,
            device_id=device_id,
            limit=limit,
            starting_after=starting_after,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self,
        *,
        device_id: str,
        amount_minor: int,
        currency: str,
        invoice_id: typing.Optional[str] = OMIT,
        reference: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TerminalPaymentResponse:
        """
        Send a card-present payment request to a specific terminal device. The payment is dispatched to the merchant's POS connector which forwards it to the PAX terminal.

        **Device Selection:** You must provide a `device_id`. Use [List Terminal Devices](#tag/Terminal-Devices/operation/terminal_devices_list) to discover available devices and their IDs. Even merchants with a single terminal must pass the `device_id` explicitly — there is no auto-routing fallback.

        **Invoice Association:** `invoice_id` is optional. Omit it for walk-in or ad-hoc payments where no pre-existing invoice exists.

        The response returns immediately with status `requested`. Subscribe to terminal webhooks (`billing.terminal_payment.succeeded`, `billing.terminal_payment.declined`, etc.) to receive the outcome asynchronously.

        Parameters
        ----------
        device_id : str
            The ID of the terminal device to send the payment to. Use List Devices to discover available device IDs. Even merchants with a single terminal must pass the device_id explicitly — there is no auto-routing fallback.

        amount_minor : int
            Amount in minor units (e.g., pence for GBP, cents for USD)

        currency : str
            ISO 4217 currency code

        invoice_id : typing.Optional[str]
            The invoice to charge. Omit for walk-in or ad-hoc payments where no invoice exists. When omitted, the terminal payment is recorded without an invoice association.

        reference : typing.Optional[str]
            Custom reference for the payment. Auto-generated if not provided.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Payment dispatched to terminal

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.terminal_payments.create(
                device_id="d1e2f3a4-b5c6-7890-abcd-ef1234567890",
                amount_minor=5000,
                currency="GBP",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            device_id=device_id,
            amount_minor=amount_minor,
            currency=currency,
            invoice_id=invoice_id,
            reference=reference,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TerminalPaymentResponse:
        """
        Get a terminal payment attempt by ID.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Terminal payment details

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.terminal_payments.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def cancel(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TerminalPaymentResponse:
        """
        Cancel an in-progress terminal payment. Only payments with status `requested` or `in_progress` can be cancelled.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Payment cancelled

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.terminal_payments.cancel(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(id, request_options=request_options)
        return _response.data

    async def refund(
        self,
        id: str,
        *,
        amount_minor: typing.Optional[int] = OMIT,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TerminalPaymentResponse:
        """
        Initiate a refund for a completed terminal payment. The refund is sent to the same terminal that processed the original sale.

        `amount_minor` is optional — omit for a full refund. For partial refunds, specify the amount in minor units.

        The refund command is dispatched asynchronously. Subscribe to `billing.terminal_refund.succeeded` webhooks for the outcome.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID of the original sale

        amount_minor : typing.Optional[int]
            Amount to refund in minor units. Omit for a full refund.

        reason : typing.Optional[str]
            Reason for the refund

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Refund dispatched to terminal

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.terminal_payments.refund(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refund(
            id, amount_minor=amount_minor, reason=reason, request_options=request_options
        )
        return _response.data

    async def void(
        self, id: str, *, reason: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> TerminalPaymentResponse:
        """
        Void a completed terminal payment. Voids are always for the full amount — partial voids are not supported. The void is sent to the same terminal that processed the original sale.

        Voids are only possible for unsettled transactions. If the transaction has already settled, use a refund instead.

        The void command is dispatched asynchronously. Subscribe to `billing.terminal_void.succeeded` webhooks for the outcome.

        Parameters
        ----------
        id : str
            Terminal payment attempt ID of the original sale

        reason : typing.Optional[str]
            Reason for the void

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TerminalPaymentResponse
            Void dispatched to terminal

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.terminal_payments.void(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.void(id, reason=reason, request_options=request_options)
        return _response.data
