# This file was auto-generated by Fern from our API Definition.

import typing

OrdersListRequestStatus = typing.Union[
    typing.Literal["draft", "pending", "paid", "partially_paid", "refunded", "canceled", "fulfilled"], typing.Any
]
