# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.discount_create_response import DiscountCreateResponse
from ..types.discount_delete_response import DiscountDeleteResponse
from ..types.discount_list_response import DiscountListResponse
from ..types.discount_retrieve_response import DiscountRetrieveResponse
from ..types.discount_update_response import DiscountUpdateResponse
from .raw_client import AsyncRawDiscountsClient, RawDiscountsClient
from .types.create_discount_input_applies_to import CreateDiscountInputAppliesTo
from .types.create_discount_input_discount_type import CreateDiscountInputDiscountType
from .types.create_discount_input_recurring_type import CreateDiscountInputRecurringType
from .types.create_discount_input_scope import CreateDiscountInputScope
from .types.discounts_list_request_is_active import DiscountsListRequestIsActive
from .types.discounts_list_request_is_archived import DiscountsListRequestIsArchived
from .types.update_discount_input_applies_to import UpdateDiscountInputAppliesTo
from .types.update_discount_input_recurring_type import UpdateDiscountInputRecurringType
from .types.update_discount_input_scope import UpdateDiscountInputScope

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DiscountsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDiscountsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDiscountsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDiscountsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        is_active: typing.Optional[DiscountsListRequestIsActive] = None,
        is_archived: typing.Optional[DiscountsListRequestIsArchived] = None,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DiscountListResponse:
        """
        Retrieve a paginated list of discounts.

        Parameters
        ----------
        is_active : typing.Optional[DiscountsListRequestIsActive]
            Filter by active status

        is_archived : typing.Optional[DiscountsListRequestIsArchived]
            Filter by archived status

        limit : typing.Optional[float]
            Number of results to return (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountListResponse
            List of discounts

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.discounts.list(
            limit=20.0,
        )
        """
        _response = self._raw_client.list(
            is_active=is_active, is_archived=is_archived, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def create(
        self,
        *,
        code: str,
        name: str,
        discount_type: CreateDiscountInputDiscountType,
        discount_value: float,
        description: typing.Optional[str] = OMIT,
        applies_to: typing.Optional[CreateDiscountInputAppliesTo] = OMIT,
        scope: typing.Optional[CreateDiscountInputScope] = OMIT,
        product_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        max_redemptions: typing.Optional[int] = OMIT,
        max_redemptions_per_user: typing.Optional[int] = OMIT,
        valid_from: typing.Optional[str] = OMIT,
        valid_until: typing.Optional[str] = OMIT,
        recurring_type: typing.Optional[CreateDiscountInputRecurringType] = OMIT,
        recurring_cycles: typing.Optional[int] = OMIT,
        first_time_customer: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DiscountCreateResponse:
        """
        Create a new discount code.

        Parameters
        ----------
        code : str
            Unique discount code (will be uppercased)

        name : str
            Human-readable name

        discount_type : CreateDiscountInputDiscountType
            Type of discount

        discount_value : float
            Discount value - percentage (1-100) or amount in cents

        description : typing.Optional[str]
            Optional description

        applies_to : typing.Optional[CreateDiscountInputAppliesTo]
            Which products the discount applies to

        scope : typing.Optional[CreateDiscountInputScope]
            Scope of where discount can be applied

        product_ids : typing.Optional[typing.Sequence[str]]
            Product IDs if applies_to is 'specific_products'

        max_redemptions : typing.Optional[int]
            Maximum total redemptions allowed

        max_redemptions_per_user : typing.Optional[int]
            Maximum redemptions per customer (0 = unlimited)

        valid_from : typing.Optional[str]
            Start date (ISO 8601)

        valid_until : typing.Optional[str]
            End date (ISO 8601)

        recurring_type : typing.Optional[CreateDiscountInputRecurringType]
            How the discount applies to recurring payments

        recurring_cycles : typing.Optional[int]
            Number of billing cycles (only if recurring_type is 'repeating')

        first_time_customer : typing.Optional[bool]
            Only available to first-time customers

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountCreateResponse
            Discount created successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.discounts.create(
            code="SUMMER20",
            name="Summer Sale 20% Off",
            discount_type="percentage",
            discount_value=20.0,
        )
        """
        _response = self._raw_client.create(
            code=code,
            name=name,
            discount_type=discount_type,
            discount_value=discount_value,
            description=description,
            applies_to=applies_to,
            scope=scope,
            product_ids=product_ids,
            max_redemptions=max_redemptions,
            max_redemptions_per_user=max_redemptions_per_user,
            valid_from=valid_from,
            valid_until=valid_until,
            recurring_type=recurring_type,
            recurring_cycles=recurring_cycles,
            first_time_customer=first_time_customer,
            request_options=request_options,
        )
        return _response.data

    def retrieve(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DiscountRetrieveResponse:
        """
        Retrieve a single discount by its ID.

        Parameters
        ----------
        id : str
            Discount ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountRetrieveResponse
            Discount details

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.discounts.retrieve(
            id="id",
        )
        """
        _response = self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DiscountDeleteResponse:
        """
        Archive a discount (soft delete). The discount code can no longer be used.

        Parameters
        ----------
        id : str
            Discount ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountDeleteResponse
            Discount archived successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.discounts.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        discount_value: typing.Optional[float] = OMIT,
        applies_to: typing.Optional[UpdateDiscountInputAppliesTo] = OMIT,
        scope: typing.Optional[UpdateDiscountInputScope] = OMIT,
        product_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        max_redemptions: typing.Optional[int] = OMIT,
        max_redemptions_per_user: typing.Optional[int] = OMIT,
        valid_from: typing.Optional[str] = OMIT,
        valid_until: typing.Optional[str] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        recurring_type: typing.Optional[UpdateDiscountInputRecurringType] = OMIT,
        recurring_cycles: typing.Optional[int] = OMIT,
        first_time_customer: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DiscountUpdateResponse:
        """
        Update an existing discount. Note: discount code and type cannot be changed.

        Parameters
        ----------
        id : str
            Discount ID

        name : typing.Optional[str]

        description : typing.Optional[str]

        discount_value : typing.Optional[float]

        applies_to : typing.Optional[UpdateDiscountInputAppliesTo]

        scope : typing.Optional[UpdateDiscountInputScope]

        product_ids : typing.Optional[typing.Sequence[str]]

        max_redemptions : typing.Optional[int]

        max_redemptions_per_user : typing.Optional[int]

        valid_from : typing.Optional[str]

        valid_until : typing.Optional[str]

        is_active : typing.Optional[bool]

        is_archived : typing.Optional[bool]

        recurring_type : typing.Optional[UpdateDiscountInputRecurringType]

        recurring_cycles : typing.Optional[int]

        first_time_customer : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountUpdateResponse
            Discount updated successfully

        Examples
        --------
        from revkeen import RevKeen

        client = RevKeen(
            api_key="YOUR_API_KEY",
        )
        client.discounts.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            description=description,
            discount_value=discount_value,
            applies_to=applies_to,
            scope=scope,
            product_ids=product_ids,
            max_redemptions=max_redemptions,
            max_redemptions_per_user=max_redemptions_per_user,
            valid_from=valid_from,
            valid_until=valid_until,
            is_active=is_active,
            is_archived=is_archived,
            recurring_type=recurring_type,
            recurring_cycles=recurring_cycles,
            first_time_customer=first_time_customer,
            request_options=request_options,
        )
        return _response.data


class AsyncDiscountsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDiscountsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDiscountsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDiscountsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        is_active: typing.Optional[DiscountsListRequestIsActive] = None,
        is_archived: typing.Optional[DiscountsListRequestIsArchived] = None,
        limit: typing.Optional[float] = None,
        offset: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DiscountListResponse:
        """
        Retrieve a paginated list of discounts.

        Parameters
        ----------
        is_active : typing.Optional[DiscountsListRequestIsActive]
            Filter by active status

        is_archived : typing.Optional[DiscountsListRequestIsArchived]
            Filter by archived status

        limit : typing.Optional[float]
            Number of results to return (1-100)

        offset : typing.Optional[float]
            Number of results to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountListResponse
            List of discounts

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.discounts.list(
                limit=20.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            is_active=is_active, is_archived=is_archived, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        code: str,
        name: str,
        discount_type: CreateDiscountInputDiscountType,
        discount_value: float,
        description: typing.Optional[str] = OMIT,
        applies_to: typing.Optional[CreateDiscountInputAppliesTo] = OMIT,
        scope: typing.Optional[CreateDiscountInputScope] = OMIT,
        product_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        max_redemptions: typing.Optional[int] = OMIT,
        max_redemptions_per_user: typing.Optional[int] = OMIT,
        valid_from: typing.Optional[str] = OMIT,
        valid_until: typing.Optional[str] = OMIT,
        recurring_type: typing.Optional[CreateDiscountInputRecurringType] = OMIT,
        recurring_cycles: typing.Optional[int] = OMIT,
        first_time_customer: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DiscountCreateResponse:
        """
        Create a new discount code.

        Parameters
        ----------
        code : str
            Unique discount code (will be uppercased)

        name : str
            Human-readable name

        discount_type : CreateDiscountInputDiscountType
            Type of discount

        discount_value : float
            Discount value - percentage (1-100) or amount in cents

        description : typing.Optional[str]
            Optional description

        applies_to : typing.Optional[CreateDiscountInputAppliesTo]
            Which products the discount applies to

        scope : typing.Optional[CreateDiscountInputScope]
            Scope of where discount can be applied

        product_ids : typing.Optional[typing.Sequence[str]]
            Product IDs if applies_to is 'specific_products'

        max_redemptions : typing.Optional[int]
            Maximum total redemptions allowed

        max_redemptions_per_user : typing.Optional[int]
            Maximum redemptions per customer (0 = unlimited)

        valid_from : typing.Optional[str]
            Start date (ISO 8601)

        valid_until : typing.Optional[str]
            End date (ISO 8601)

        recurring_type : typing.Optional[CreateDiscountInputRecurringType]
            How the discount applies to recurring payments

        recurring_cycles : typing.Optional[int]
            Number of billing cycles (only if recurring_type is 'repeating')

        first_time_customer : typing.Optional[bool]
            Only available to first-time customers

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountCreateResponse
            Discount created successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.discounts.create(
                code="SUMMER20",
                name="Summer Sale 20% Off",
                discount_type="percentage",
                discount_value=20.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            code=code,
            name=name,
            discount_type=discount_type,
            discount_value=discount_value,
            description=description,
            applies_to=applies_to,
            scope=scope,
            product_ids=product_ids,
            max_redemptions=max_redemptions,
            max_redemptions_per_user=max_redemptions_per_user,
            valid_from=valid_from,
            valid_until=valid_until,
            recurring_type=recurring_type,
            recurring_cycles=recurring_cycles,
            first_time_customer=first_time_customer,
            request_options=request_options,
        )
        return _response.data

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DiscountRetrieveResponse:
        """
        Retrieve a single discount by its ID.

        Parameters
        ----------
        id : str
            Discount ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountRetrieveResponse
            Discount details

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.discounts.retrieve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(id, request_options=request_options)
        return _response.data

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DiscountDeleteResponse:
        """
        Archive a discount (soft delete). The discount code can no longer be used.

        Parameters
        ----------
        id : str
            Discount ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountDeleteResponse
            Discount archived successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.discounts.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        discount_value: typing.Optional[float] = OMIT,
        applies_to: typing.Optional[UpdateDiscountInputAppliesTo] = OMIT,
        scope: typing.Optional[UpdateDiscountInputScope] = OMIT,
        product_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        max_redemptions: typing.Optional[int] = OMIT,
        max_redemptions_per_user: typing.Optional[int] = OMIT,
        valid_from: typing.Optional[str] = OMIT,
        valid_until: typing.Optional[str] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        is_archived: typing.Optional[bool] = OMIT,
        recurring_type: typing.Optional[UpdateDiscountInputRecurringType] = OMIT,
        recurring_cycles: typing.Optional[int] = OMIT,
        first_time_customer: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DiscountUpdateResponse:
        """
        Update an existing discount. Note: discount code and type cannot be changed.

        Parameters
        ----------
        id : str
            Discount ID

        name : typing.Optional[str]

        description : typing.Optional[str]

        discount_value : typing.Optional[float]

        applies_to : typing.Optional[UpdateDiscountInputAppliesTo]

        scope : typing.Optional[UpdateDiscountInputScope]

        product_ids : typing.Optional[typing.Sequence[str]]

        max_redemptions : typing.Optional[int]

        max_redemptions_per_user : typing.Optional[int]

        valid_from : typing.Optional[str]

        valid_until : typing.Optional[str]

        is_active : typing.Optional[bool]

        is_archived : typing.Optional[bool]

        recurring_type : typing.Optional[UpdateDiscountInputRecurringType]

        recurring_cycles : typing.Optional[int]

        first_time_customer : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DiscountUpdateResponse
            Discount updated successfully

        Examples
        --------
        import asyncio

        from revkeen import AsyncRevKeen

        client = AsyncRevKeen(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.discounts.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            description=description,
            discount_value=discount_value,
            applies_to=applies_to,
            scope=scope,
            product_ids=product_ids,
            max_redemptions=max_redemptions,
            max_redemptions_per_user=max_redemptions_per_user,
            valid_from=valid_from,
            valid_until=valid_until,
            is_active=is_active,
            is_archived=is_archived,
            recurring_type=recurring_type,
            recurring_cycles=recurring_cycles,
            first_time_customer=first_time_customer,
            request_options=request_options,
        )
        return _response.data
