# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .invoices_credit_note_issue_request_credit_method import InvoicesCreditNoteIssueRequestCreditMethod
    from .invoices_credit_note_issue_request_reason_code import InvoicesCreditNoteIssueRequestReasonCode
    from .invoices_external_batch_request_invoices_item import InvoicesExternalBatchRequestInvoicesItem
    from .invoices_external_batch_request_invoices_item_customer_external_ref import (
        InvoicesExternalBatchRequestInvoicesItemCustomerExternalRef,
    )
    from .invoices_external_batch_request_invoices_item_line_items_item import (
        InvoicesExternalBatchRequestInvoicesItemLineItemsItem,
    )
    from .invoices_external_batch_response import InvoicesExternalBatchResponse
    from .invoices_external_batch_response_failed_item import InvoicesExternalBatchResponseFailedItem
    from .invoices_external_upsert_by_external_id_request_customer_external_ref import (
        InvoicesExternalUpsertByExternalIdRequestCustomerExternalRef,
    )
    from .invoices_external_upsert_by_external_id_request_line_items_item import (
        InvoicesExternalUpsertByExternalIdRequestLineItemsItem,
    )
    from .invoices_external_upsert_by_external_id_response import InvoicesExternalUpsertByExternalIdResponse
    from .invoices_pay_request_payment_method import InvoicesPayRequestPaymentMethod
    from .invoices_send_request_channel import InvoicesSendRequestChannel
    from .invoices_update_request_subscription_terms import InvoicesUpdateRequestSubscriptionTerms
    from .invoices_update_request_subscription_terms_collection_method import (
        InvoicesUpdateRequestSubscriptionTermsCollectionMethod,
    )
    from .invoices_update_request_subscription_terms_duration_type import (
        InvoicesUpdateRequestSubscriptionTermsDurationType,
    )
    from .invoices_update_request_subscription_terms_first_payment_behavior import (
        InvoicesUpdateRequestSubscriptionTermsFirstPaymentBehavior,
    )
    from .invoices_update_request_subscription_terms_start_mode import InvoicesUpdateRequestSubscriptionTermsStartMode
_dynamic_imports: typing.Dict[str, str] = {
    "InvoicesCreditNoteIssueRequestCreditMethod": ".invoices_credit_note_issue_request_credit_method",
    "InvoicesCreditNoteIssueRequestReasonCode": ".invoices_credit_note_issue_request_reason_code",
    "InvoicesExternalBatchRequestInvoicesItem": ".invoices_external_batch_request_invoices_item",
    "InvoicesExternalBatchRequestInvoicesItemCustomerExternalRef": ".invoices_external_batch_request_invoices_item_customer_external_ref",
    "InvoicesExternalBatchRequestInvoicesItemLineItemsItem": ".invoices_external_batch_request_invoices_item_line_items_item",
    "InvoicesExternalBatchResponse": ".invoices_external_batch_response",
    "InvoicesExternalBatchResponseFailedItem": ".invoices_external_batch_response_failed_item",
    "InvoicesExternalUpsertByExternalIdRequestCustomerExternalRef": ".invoices_external_upsert_by_external_id_request_customer_external_ref",
    "InvoicesExternalUpsertByExternalIdRequestLineItemsItem": ".invoices_external_upsert_by_external_id_request_line_items_item",
    "InvoicesExternalUpsertByExternalIdResponse": ".invoices_external_upsert_by_external_id_response",
    "InvoicesPayRequestPaymentMethod": ".invoices_pay_request_payment_method",
    "InvoicesSendRequestChannel": ".invoices_send_request_channel",
    "InvoicesUpdateRequestSubscriptionTerms": ".invoices_update_request_subscription_terms",
    "InvoicesUpdateRequestSubscriptionTermsCollectionMethod": ".invoices_update_request_subscription_terms_collection_method",
    "InvoicesUpdateRequestSubscriptionTermsDurationType": ".invoices_update_request_subscription_terms_duration_type",
    "InvoicesUpdateRequestSubscriptionTermsFirstPaymentBehavior": ".invoices_update_request_subscription_terms_first_payment_behavior",
    "InvoicesUpdateRequestSubscriptionTermsStartMode": ".invoices_update_request_subscription_terms_start_mode",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "InvoicesCreditNoteIssueRequestCreditMethod",
    "InvoicesCreditNoteIssueRequestReasonCode",
    "InvoicesExternalBatchRequestInvoicesItem",
    "InvoicesExternalBatchRequestInvoicesItemCustomerExternalRef",
    "InvoicesExternalBatchRequestInvoicesItemLineItemsItem",
    "InvoicesExternalBatchResponse",
    "InvoicesExternalBatchResponseFailedItem",
    "InvoicesExternalUpsertByExternalIdRequestCustomerExternalRef",
    "InvoicesExternalUpsertByExternalIdRequestLineItemsItem",
    "InvoicesExternalUpsertByExternalIdResponse",
    "InvoicesPayRequestPaymentMethod",
    "InvoicesSendRequestChannel",
    "InvoicesUpdateRequestSubscriptionTerms",
    "InvoicesUpdateRequestSubscriptionTermsCollectionMethod",
    "InvoicesUpdateRequestSubscriptionTermsDurationType",
    "InvoicesUpdateRequestSubscriptionTermsFirstPaymentBehavior",
    "InvoicesUpdateRequestSubscriptionTermsStartMode",
]
