# This file was auto-generated by Fern from our API Definition.

import typing

InvoicesUpdateRequestSubscriptionTermsStartMode = typing.Union[
    typing.Literal["when_paid", "on_invoice_date", "first_of_next_month", "specific_date"], typing.Any
]
