# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.payment_intent import PaymentIntent
from ..types.payment_intent_list_response import PaymentIntentListResponse
from .types.cancel_payment_intent_request_cancellation_reason import CancelPaymentIntentRequestCancellationReason
from .types.create_payment_intent_request_capture_method import CreatePaymentIntentRequestCaptureMethod
from .types.payment_intents_list_request_status import PaymentIntentsListRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPaymentIntentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        customer: typing.Optional[str] = None,
        status: typing.Optional[PaymentIntentsListRequestStatus] = None,
        created_gte: typing.Optional[float] = None,
        created_lte: typing.Optional[float] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaymentIntentListResponse]:
        """
        Returns a list of payment intents with optional filtering.

        Parameters
        ----------
        customer : typing.Optional[str]
            Filter by customer ID

        status : typing.Optional[PaymentIntentsListRequestStatus]
            Filter by status

        created_gte : typing.Optional[float]
            Filter by created_at >= (Unix timestamp)

        created_lte : typing.Optional[float]
            Filter by created_at <= (Unix timestamp)

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        starting_after : typing.Optional[str]
            Cursor for pagination - return results after this ID (pi_xxx)

        ending_before : typing.Optional[str]
            Cursor for pagination - return results before this ID (pi_xxx)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntentListResponse]
            List of payment intents
        """
        _response = self._client_wrapper.httpx_client.request(
            "payment-intents",
            method="GET",
            params={
                "customer": customer,
                "status": status,
                "created_gte": created_gte,
                "created_lte": created_lte,
                "limit": limit,
                "starting_after": starting_after,
                "ending_before": ending_before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntentListResponse,
                    parse_obj_as(
                        type_=PaymentIntentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        amount: int,
        customer: str,
        currency: typing.Optional[str] = OMIT,
        payment_method: typing.Optional[str] = OMIT,
        capture_method: typing.Optional[CreatePaymentIntentRequestCaptureMethod] = OMIT,
        description: typing.Optional[str] = OMIT,
        statement_descriptor: typing.Optional[str] = OMIT,
        statement_descriptor_suffix: typing.Optional[str] = OMIT,
        receipt_email: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        gateway_merchant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaymentIntent]:
        """
        Creates a payment intent to orchestrate payment collection with support for 3DS/SCA authentication.

        Parameters
        ----------
        amount : int
            Amount in cents. Must be greater than 0.

        customer : str
            Customer ID to charge

        currency : typing.Optional[str]
            Three-letter ISO currency code. Defaults to USD.

        payment_method : typing.Optional[str]
            Payment method ID. If not provided, status will be requires_payment_method.

        capture_method : typing.Optional[CreatePaymentIntentRequestCaptureMethod]
            Capture method. Defaults to automatic.

        description : typing.Optional[str]
            Description for merchant reference

        statement_descriptor : typing.Optional[str]
            Statement descriptor shown on customer's statement

        statement_descriptor_suffix : typing.Optional[str]
            Statement descriptor suffix

        receipt_email : typing.Optional[str]
            Email to send receipt to

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom key-value metadata

        gateway_merchant_id : typing.Optional[str]
            Specific gateway merchant ID for multi-MID setups (NMI)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntent]
            Payment intent created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "payment-intents",
            method="POST",
            json={
                "amount": amount,
                "currency": currency,
                "customer": customer,
                "payment_method": payment_method,
                "capture_method": capture_method,
                "description": description,
                "statement_descriptor": statement_descriptor,
                "statement_descriptor_suffix": statement_descriptor_suffix,
                "receipt_email": receipt_email,
                "metadata": metadata,
                "gateway_merchant_id": gateway_merchant_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PaymentIntent]:
        """
        Retrieves a payment intent by its ID (pi_xxx).

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntent]
            Payment intent details
        """
        _response = self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        id: str,
        *,
        amount: typing.Optional[int] = OMIT,
        currency: typing.Optional[str] = OMIT,
        payment_method: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        statement_descriptor: typing.Optional[str] = OMIT,
        statement_descriptor_suffix: typing.Optional[str] = OMIT,
        receipt_email: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaymentIntent]:
        """
        Updates a payment intent. Only certain fields can be updated based on the intent's status.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        amount : typing.Optional[int]
            Amount in cents

        currency : typing.Optional[str]
            Three-letter ISO currency code

        payment_method : typing.Optional[str]
            Payment method ID

        description : typing.Optional[str]
            Description for merchant reference

        statement_descriptor : typing.Optional[str]
            Statement descriptor

        statement_descriptor_suffix : typing.Optional[str]
            Statement descriptor suffix

        receipt_email : typing.Optional[str]
            Email to send receipt to

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom key-value metadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntent]
            Updated payment intent
        """
        _response = self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}",
            method="POST",
            json={
                "amount": amount,
                "currency": currency,
                "payment_method": payment_method,
                "description": description,
                "statement_descriptor": statement_descriptor,
                "statement_descriptor_suffix": statement_descriptor_suffix,
                "receipt_email": receipt_email,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def confirm(
        self,
        id: str,
        *,
        payment_method: typing.Optional[str] = OMIT,
        return_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaymentIntent]:
        """
        Confirms the payment intent. May return requires_action if 3DS authentication is needed.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        payment_method : typing.Optional[str]
            Payment method ID. Required if not already set on the intent.

        return_url : typing.Optional[str]
            URL to redirect to after 3DS authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntent]
            Confirmed payment intent
        """
        _response = self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}/confirm",
            method="POST",
            json={
                "payment_method": payment_method,
                "return_url": return_url,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def capture(
        self,
        id: str,
        *,
        amount_to_capture: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaymentIntent]:
        """
        Captures a payment intent that was created with capture_method=manual.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        amount_to_capture : typing.Optional[int]
            Amount to capture in cents. Defaults to full authorized amount.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntent]
            Captured payment intent
        """
        _response = self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}/capture",
            method="POST",
            json={
                "amount_to_capture": amount_to_capture,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel(
        self,
        id: str,
        *,
        cancellation_reason: typing.Optional[CancelPaymentIntentRequestCancellationReason] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaymentIntent]:
        """
        Cancels a payment intent. Cannot cancel if already succeeded or canceled.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        cancellation_reason : typing.Optional[CancelPaymentIntentRequestCancellationReason]
            Reason for cancellation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaymentIntent]
            Canceled payment intent
        """
        _response = self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}/cancel",
            method="POST",
            json={
                "cancellation_reason": cancellation_reason,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPaymentIntentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        customer: typing.Optional[str] = None,
        status: typing.Optional[PaymentIntentsListRequestStatus] = None,
        created_gte: typing.Optional[float] = None,
        created_lte: typing.Optional[float] = None,
        limit: typing.Optional[int] = None,
        starting_after: typing.Optional[str] = None,
        ending_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaymentIntentListResponse]:
        """
        Returns a list of payment intents with optional filtering.

        Parameters
        ----------
        customer : typing.Optional[str]
            Filter by customer ID

        status : typing.Optional[PaymentIntentsListRequestStatus]
            Filter by status

        created_gte : typing.Optional[float]
            Filter by created_at >= (Unix timestamp)

        created_lte : typing.Optional[float]
            Filter by created_at <= (Unix timestamp)

        limit : typing.Optional[int]
            Maximum number of results (1-100)

        starting_after : typing.Optional[str]
            Cursor for pagination - return results after this ID (pi_xxx)

        ending_before : typing.Optional[str]
            Cursor for pagination - return results before this ID (pi_xxx)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntentListResponse]
            List of payment intents
        """
        _response = await self._client_wrapper.httpx_client.request(
            "payment-intents",
            method="GET",
            params={
                "customer": customer,
                "status": status,
                "created_gte": created_gte,
                "created_lte": created_lte,
                "limit": limit,
                "starting_after": starting_after,
                "ending_before": ending_before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntentListResponse,
                    parse_obj_as(
                        type_=PaymentIntentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        amount: int,
        customer: str,
        currency: typing.Optional[str] = OMIT,
        payment_method: typing.Optional[str] = OMIT,
        capture_method: typing.Optional[CreatePaymentIntentRequestCaptureMethod] = OMIT,
        description: typing.Optional[str] = OMIT,
        statement_descriptor: typing.Optional[str] = OMIT,
        statement_descriptor_suffix: typing.Optional[str] = OMIT,
        receipt_email: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        gateway_merchant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaymentIntent]:
        """
        Creates a payment intent to orchestrate payment collection with support for 3DS/SCA authentication.

        Parameters
        ----------
        amount : int
            Amount in cents. Must be greater than 0.

        customer : str
            Customer ID to charge

        currency : typing.Optional[str]
            Three-letter ISO currency code. Defaults to USD.

        payment_method : typing.Optional[str]
            Payment method ID. If not provided, status will be requires_payment_method.

        capture_method : typing.Optional[CreatePaymentIntentRequestCaptureMethod]
            Capture method. Defaults to automatic.

        description : typing.Optional[str]
            Description for merchant reference

        statement_descriptor : typing.Optional[str]
            Statement descriptor shown on customer's statement

        statement_descriptor_suffix : typing.Optional[str]
            Statement descriptor suffix

        receipt_email : typing.Optional[str]
            Email to send receipt to

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom key-value metadata

        gateway_merchant_id : typing.Optional[str]
            Specific gateway merchant ID for multi-MID setups (NMI)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntent]
            Payment intent created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "payment-intents",
            method="POST",
            json={
                "amount": amount,
                "currency": currency,
                "customer": customer,
                "payment_method": payment_method,
                "capture_method": capture_method,
                "description": description,
                "statement_descriptor": statement_descriptor,
                "statement_descriptor_suffix": statement_descriptor_suffix,
                "receipt_email": receipt_email,
                "metadata": metadata,
                "gateway_merchant_id": gateway_merchant_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def retrieve(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PaymentIntent]:
        """
        Retrieves a payment intent by its ID (pi_xxx).

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntent]
            Payment intent details
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        id: str,
        *,
        amount: typing.Optional[int] = OMIT,
        currency: typing.Optional[str] = OMIT,
        payment_method: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        statement_descriptor: typing.Optional[str] = OMIT,
        statement_descriptor_suffix: typing.Optional[str] = OMIT,
        receipt_email: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaymentIntent]:
        """
        Updates a payment intent. Only certain fields can be updated based on the intent's status.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        amount : typing.Optional[int]
            Amount in cents

        currency : typing.Optional[str]
            Three-letter ISO currency code

        payment_method : typing.Optional[str]
            Payment method ID

        description : typing.Optional[str]
            Description for merchant reference

        statement_descriptor : typing.Optional[str]
            Statement descriptor

        statement_descriptor_suffix : typing.Optional[str]
            Statement descriptor suffix

        receipt_email : typing.Optional[str]
            Email to send receipt to

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom key-value metadata

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntent]
            Updated payment intent
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}",
            method="POST",
            json={
                "amount": amount,
                "currency": currency,
                "payment_method": payment_method,
                "description": description,
                "statement_descriptor": statement_descriptor,
                "statement_descriptor_suffix": statement_descriptor_suffix,
                "receipt_email": receipt_email,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def confirm(
        self,
        id: str,
        *,
        payment_method: typing.Optional[str] = OMIT,
        return_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaymentIntent]:
        """
        Confirms the payment intent. May return requires_action if 3DS authentication is needed.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        payment_method : typing.Optional[str]
            Payment method ID. Required if not already set on the intent.

        return_url : typing.Optional[str]
            URL to redirect to after 3DS authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntent]
            Confirmed payment intent
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}/confirm",
            method="POST",
            json={
                "payment_method": payment_method,
                "return_url": return_url,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def capture(
        self,
        id: str,
        *,
        amount_to_capture: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaymentIntent]:
        """
        Captures a payment intent that was created with capture_method=manual.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        amount_to_capture : typing.Optional[int]
            Amount to capture in cents. Defaults to full authorized amount.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntent]
            Captured payment intent
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}/capture",
            method="POST",
            json={
                "amount_to_capture": amount_to_capture,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel(
        self,
        id: str,
        *,
        cancellation_reason: typing.Optional[CancelPaymentIntentRequestCancellationReason] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaymentIntent]:
        """
        Cancels a payment intent. Cannot cancel if already succeeded or canceled.

        Parameters
        ----------
        id : str
            Payment intent ID (pi_xxx)

        cancellation_reason : typing.Optional[CancelPaymentIntentRequestCancellationReason]
            Reason for cancellation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaymentIntent]
            Canceled payment intent
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"payment-intents/{jsonable_encoder(id)}/cancel",
            method="POST",
            json={
                "cancellation_reason": cancellation_reason,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaymentIntent,
                    parse_obj_as(
                        type_=PaymentIntent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
