# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_clients_id_configured_currencies_response_currency_details_item import (
    GetClientsIdConfiguredCurrenciesResponseCurrencyDetailsItem,
)


class GetClientsIdConfiguredCurrenciesResponse(UniversalBaseModel):
    success: bool
    currencies: typing.List[str]
    default_currency: typing.Optional[str] = None
    currency_details: typing.List[GetClientsIdConfiguredCurrenciesResponseCurrencyDetailsItem]
    request_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="requestId")] = pydantic.Field(
        alias="requestId", default=None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
