# This file was auto-generated by Fern from our API Definition.

import typing

CustomersOrdersListRequestStatus = typing.Union[typing.Literal["pending", "paid", "fulfilled", "canceled"], typing.Any]
