# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .customers_external_upsert_by_external_id_response_created_data import (
    CustomersExternalUpsertByExternalIdResponseCreatedData,
)


class CustomersExternalUpsertByExternalIdResponseCreated(UniversalBaseModel):
    data: CustomersExternalUpsertByExternalIdResponseCreatedData
    created: bool
    warnings: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
