# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.customer_subscription import CustomerSubscription
from .customers_subscriptions_list_response_object import CustomersSubscriptionsListResponseObject


class CustomersSubscriptionsListResponse(UniversalBaseModel):
    object: CustomersSubscriptionsListResponseObject
    data: typing.List[CustomerSubscription]
    has_more: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
