# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .analytics_invoices_get_ar_aging_response_buckets_item import AnalyticsInvoicesGetArAgingResponseBucketsItem


class AnalyticsInvoicesGetArAgingResponse(UniversalBaseModel):
    as_of_date: typing_extensions.Annotated[str, FieldMetadata(alias="asOfDate")] = pydantic.Field(alias="asOfDate")
    buckets: typing.List[AnalyticsInvoicesGetArAgingResponseBucketsItem]
    total_outstanding: typing_extensions.Annotated[float, FieldMetadata(alias="totalOutstanding")] = pydantic.Field(
        alias="totalOutstanding"
    )
    total_invoices: typing_extensions.Annotated[float, FieldMetadata(alias="totalInvoices")] = pydantic.Field(
        alias="totalInvoices"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
