# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class AnalyticsCustomersRetrieveResponse(UniversalBaseModel):
    customer_id: typing_extensions.Annotated[str, FieldMetadata(alias="customerId")] = pydantic.Field(
        alias="customerId"
    )
    total_revenue: typing_extensions.Annotated[float, FieldMetadata(alias="totalRevenue")] = pydantic.Field(
        alias="totalRevenue"
    )
    total_invoices: typing_extensions.Annotated[float, FieldMetadata(alias="totalInvoices")] = pydantic.Field(
        alias="totalInvoices"
    )
    avg_invoice_value: typing_extensions.Annotated[float, FieldMetadata(alias="avgInvoiceValue")] = pydantic.Field(
        alias="avgInvoiceValue"
    )
    outstanding_balance: typing_extensions.Annotated[float, FieldMetadata(alias="outstandingBalance")] = pydantic.Field(
        alias="outstandingBalance"
    )
    payment_history: typing_extensions.Annotated[
        typing.List[typing.Dict[str, typing.Any]], FieldMetadata(alias="paymentHistory")
    ] = pydantic.Field(alias="paymentHistory")
    """
    Payment history records
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
