# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class AnalyticsPaymentLinksGetConversionResponse(UniversalBaseModel):
    total_links: typing_extensions.Annotated[float, FieldMetadata(alias="totalLinks")] = pydantic.Field(
        alias="totalLinks"
    )
    view_count: typing_extensions.Annotated[float, FieldMetadata(alias="viewCount")] = pydantic.Field(alias="viewCount")
    conversion_count: typing_extensions.Annotated[float, FieldMetadata(alias="conversionCount")] = pydantic.Field(
        alias="conversionCount"
    )
    conversion_rate: typing_extensions.Annotated[float, FieldMetadata(alias="conversionRate")] = pydantic.Field(
        alias="conversionRate"
    )
    total_revenue: typing_extensions.Annotated[float, FieldMetadata(alias="totalRevenue")] = pydantic.Field(
        alias="totalRevenue"
    )
    avg_revenue_per_conversion: typing_extensions.Annotated[float, FieldMetadata(alias="avgRevenuePerConversion")] = (
        pydantic.Field(alias="avgRevenuePerConversion")
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
