# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .analytics_revenue_get_time_series_response_data_points_item import (
    AnalyticsRevenueGetTimeSeriesResponseDataPointsItem,
)


class AnalyticsRevenueGetTimeSeriesResponse(UniversalBaseModel):
    data_points: typing_extensions.Annotated[
        typing.List[AnalyticsRevenueGetTimeSeriesResponseDataPointsItem], FieldMetadata(alias="dataPoints")
    ] = pydantic.Field(alias="dataPoints")
    total_revenue: typing_extensions.Annotated[float, FieldMetadata(alias="totalRevenue")] = pydantic.Field(
        alias="totalRevenue"
    )
    total_invoices: typing_extensions.Annotated[float, FieldMetadata(alias="totalInvoices")] = pydantic.Field(
        alias="totalInvoices"
    )
    period_start: typing_extensions.Annotated[str, FieldMetadata(alias="periodStart")] = pydantic.Field(
        alias="periodStart"
    )
    period_end: typing_extensions.Annotated[str, FieldMetadata(alias="periodEnd")] = pydantic.Field(alias="periodEnd")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
