# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class AnalyticsCheckoutAbandonmentListResponseAlertsItem(UniversalBaseModel):
    id: str
    checkout_session_id: typing_extensions.Annotated[str, FieldMetadata(alias="checkoutSessionId")] = pydantic.Field(
        alias="checkoutSessionId"
    )
    customer_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="customerId")] = pydantic.Field(
        alias="customerId", default=None
    )
    customer_email: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="customerEmail")] = (
        pydantic.Field(alias="customerEmail", default=None)
    )
    severity: str
    status: str
    cart_value_cents: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="cartValueCents")] = (
        pydantic.Field(alias="cartValueCents", default=None)
    )
    currency: str
    last_step_reached: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastStepReached")] = (
        pydantic.Field(alias="lastStepReached", default=None)
    )
    entered_email: typing_extensions.Annotated[bool, FieldMetadata(alias="enteredEmail")] = pydantic.Field(
        alias="enteredEmail"
    )
    entered_payment_info: typing_extensions.Annotated[bool, FieldMetadata(alias="enteredPaymentInfo")] = pydantic.Field(
        alias="enteredPaymentInfo"
    )
    payment_attempted: typing_extensions.Annotated[bool, FieldMetadata(alias="paymentAttempted")] = pydantic.Field(
        alias="paymentAttempted"
    )
    time_spent_seconds: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="timeSpentSeconds")] = (
        pydantic.Field(alias="timeSpentSeconds", default=None)
    )
    abandoned_at: typing_extensions.Annotated[str, FieldMetadata(alias="abandonedAt")] = pydantic.Field(
        alias="abandonedAt"
    )
    detected_at: typing_extensions.Annotated[str, FieldMetadata(alias="detectedAt")] = pydantic.Field(
        alias="detectedAt"
    )
    recovery_email_sent: typing_extensions.Annotated[bool, FieldMetadata(alias="recoveryEmailSent")] = pydantic.Field(
        alias="recoveryEmailSent"
    )
    webhook_notified: typing_extensions.Annotated[bool, FieldMetadata(alias="webhookNotified")] = pydantic.Field(
        alias="webhookNotified"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
