# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .analytics_checkout_abandonment_list_response_alerts_item import AnalyticsCheckoutAbandonmentListResponseAlertsItem


class AnalyticsCheckoutAbandonmentListResponse(UniversalBaseModel):
    alerts: typing.List[AnalyticsCheckoutAbandonmentListResponseAlertsItem]
    total: float
    page: float
    page_size: typing_extensions.Annotated[float, FieldMetadata(alias="pageSize")] = pydantic.Field(alias="pageSize")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
