# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .analytics_checkout_get_funnel_response_steps_item import AnalyticsCheckoutGetFunnelResponseStepsItem


class AnalyticsCheckoutGetFunnelResponse(UniversalBaseModel):
    start_date: typing_extensions.Annotated[str, FieldMetadata(alias="startDate")] = pydantic.Field(alias="startDate")
    end_date: typing_extensions.Annotated[str, FieldMetadata(alias="endDate")] = pydantic.Field(alias="endDate")
    total_sessions: typing_extensions.Annotated[float, FieldMetadata(alias="totalSessions")] = pydantic.Field(
        alias="totalSessions"
    )
    completed_sessions: typing_extensions.Annotated[float, FieldMetadata(alias="completedSessions")] = pydantic.Field(
        alias="completedSessions"
    )
    overall_conversion_rate: typing_extensions.Annotated[float, FieldMetadata(alias="overallConversionRate")] = (
        pydantic.Field(alias="overallConversionRate")
    )
    steps: typing.List[AnalyticsCheckoutGetFunnelResponseStepsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
