# This file was auto-generated by Fern from our API Definition.

import typing

AnalyticsRevenueGetTimeSeriesRequestGranularity = typing.Union[
    typing.Literal["day", "week", "month", "quarter", "year"], typing.Any
]
